import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'pt' | 'en' | 'es'
type Params = Record<string, string | number>

const pt = {
  'meta.title': '$ENSI - Aquecimento, sensibilidade e diagnostico FPS',
  'calibration.targetSpeed': 'Velocidade da bolinha',
  'buttons.mouse': 'Mouse',
  'common.stability': 'Estabilidade', 'common.samples': 'Amostras',
  'language.selector': 'Idioma da página',
  'nav.routine': 'Rotina', 'nav.warmup': 'Aquecimento', 'nav.calibration': 'Calibração Sensi', 'nav.converter': 'Conversor', 'nav.polling': 'Polling Rate', 'nav.buttons': 'Teste de botões',
  'header.rounds': '{completed}/{total} rodadas', 'header.openSettings': 'Abrir configurações', 'header.dailyRoutine': 'Rotina diária', 'header.aimTraining': 'Treino de mira', 'header.conversion': 'Conversão 360°', 'header.inputDiagnostics': 'Diagnóstico de entrada', 'header.mouseDiagnostics': 'Diagnóstico do mouse',
  'common.accuracy': 'Precisão', 'common.meanError': 'Erro médio', 'common.smoothness': 'Suavidade', 'common.sensitivity': 'Sensibilidade', 'common.time': 'Tempo', 'common.score': 'Score', 'common.result': 'Resultado', 'common.restart': 'Reiniciar', 'common.close': 'Fechar', 'common.mouseDpi': 'DPI do mouse', 'common.gameReference': 'Jogo de referência',
  'calibration.live': 'Ao vivo', 'calibration.roundOf': 'Rodada {round} de {total}', 'calibration.testSensitivity': 'Sensibilidade em teste', 'calibration.speed': 'Velocidade {speed}', 'calibration.prepareHand': 'Prepare a mão. A rodada ainda não pontua.', 'calibration.warmup': 'A bolinha já está em movimento. Use este segundo para encaixar o tracking.', 'calibration.guidance': 'Faça movimentos naturais. A bolinha segue velocidade fixa com mudanças aleatórias de direção.', 'calibration.trackingActive': 'Tracking ativo · se soltar, clique na arena', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pausar', 'calibration.resume': 'Retomar',
  'calibration.setupTitle': 'Configurar antes do teste', 'calibration.setupDescription': 'Escolha o jogo, informe sua sensibilidade atual e selecione a velocidade da bolinha. O teste usa {rounds} rodadas de {seconds} segundos para calibrar a mira.', 'calibration.currentSensitivity': 'Sensibilidade atual no {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Rápido', 'calibration.fastBadge': 'Rápida', 'calibration.normalDescription': 'Velocidade equilibrada para calibração padrão', 'calibration.fastDescription': 'Bolinha mais rápida para tracking mais exigente', 'calibration.crosshairType': 'Tipo de mira', 'calibration.baseSensitivity': 'Sensibilidade base em {game}', 'calibration.saveStart': 'Salvar e iniciar teste', 'calibration.save': 'Salvar configuração',
  'calibration.landingTitle': 'Descubra sua sensibilidade ideal', 'calibration.landingDescription': 'Cinco rodadas de tracking analisam sua precisão, erro médio e suavidade para encontrar o melhor equilíbrio para sua mira.', 'calibration.landingStart': 'Iniciar calibração', 'calibration.landingPreview': 'Demonstração do tracking', 'calibration.landingRoundsLabel': 'rodadas', 'calibration.landingSecondsLabel': 'segundos cada', 'calibration.landingGameResult': 'Resultado para seu jogo', 'calibration.landingStepConfigure': 'Configure', 'calibration.landingStepConfigureDescription': 'Escolha o jogo, sua sensibilidade atual e o DPI do mouse.', 'calibration.landingStepTrack': 'Faça o tracking', 'calibration.landingStepTrackDescription': 'Acompanhe o alvo enquanto testamos pequenas variações.', 'calibration.landingStepResult': 'Receba o resultado', 'calibration.landingStepResultDescription': 'Veja somente a sensibilidade recomendada para o jogo escolhido.',
  'crosshair.classic': 'Clássica', 'crosshair.dot': 'Bolinha', 'crosshair.circle': 'Circular', 'crosshair.plus': 'Cruz cheia', 'crosshair.classicDescription': 'Linhas finas com centro aberto', 'crosshair.dotDescription': 'Ponto central limpo', 'crosshair.circleDescription': 'Anel com ponto central', 'crosshair.plusDescription': 'Mira compacta e direta',
  'calibration.resultTitle': 'Sensibilidade recomendada', 'calibration.resultDescription': 'Seu melhor equilíbrio entre precisão, controle e suavidade apareceu em {multiplier}× da configuração inicial com velocidade {speed}.', 'calibration.disclaimer': 'Estimativa baseada nesta sessão. Valide a recomendação no campo de treino do jogo antes de competir.', 'calibration.redo': 'Refazer calibração',
  'arena.currentRound': 'Rodada atual', 'arena.calibrationComplete': 'Calibração concluída', 'arena.roundComplete': 'Rodada concluída', 'arena.ready': 'Tudo pronto para calibrar', 'arena.fiveRounds': 'As cinco rodadas foram registradas.', 'arena.continueReady': 'Continue quando estiver preparado.', 'arena.startHint': 'Inicie o teste para preparar a primeira rodada.', 'arena.viewResult': 'Ver resultado', 'arena.nextRound': 'Próxima rodada', 'arena.startTest': 'Iniciar teste', 'arena.notScoring': 'A rodada ainda não está pontuando', 'arena.lockCursor': 'Clique para travar o cursor', 'arena.testSensitivity': 'Sensi em teste',
  'warmup.kicker': 'Aquecimento FPS', 'warmup.title': 'Prepare a mira antes da partida', 'warmup.subtitle': 'Escolha um exercício de 1 minuto, ajuste a dificuldade e entre no ritmo com a sensibilidade do seu jogo.', 'warmup.configure': 'Configurar treino', 'warmup.configureExercise': 'Configurar {exercise}', 'warmup.sessionDuration': '{description} A sessão dura {seconds} segundos.', 'warmup.difficulty': 'Dificuldade', 'warmup.crosshair': 'Mira', 'warmup.start': 'Iniciar aquecimento', 'warmup.complete': 'Aquecimento concluído', 'warmup.level': 'Nível', 'warmup.timeOnTarget': 'Tempo no alvo', 'warmup.hits': 'Acertos', 'warmup.chooseTraining': 'Escolher treino', 'warmup.repeat': 'Repetir', 'warmup.prepareAim': 'Prepare a mira',
  'warmup.stepGame': 'Jogo', 'warmup.stepSettings': 'Ajustes', 'warmup.stepCrosshair': 'Mira', 'warmup.chooseGame': 'Escolha seu jogo', 'warmup.settingsTitle': 'Ajuste sua sensibilidade', 'warmup.crosshairTitle': 'Escolha sua mira', 'warmup.back': 'Voltar', 'warmup.next': 'Continuar', 'warmup.exit': 'Sair', 'warmup.nextRound': 'Próxima rodada', 'warmup.nextLevelHint': 'Próximo nível recomendado: {level}', 'warmup.keepHardHint': 'Continue no nível Difícil e tente superar seu resultado.', 'warmup.adaptiveNextHint': 'A próxima rodada será ajustada para {level}.', 'warmup.fixedNextHint': 'A próxima rodada terá uma nova trajetória no nível {level}.',
  'warmup.switch.name': 'Troca de alvo', 'warmup.switch.description': 'Segure a mira sobre a bola até ela desaparecer e surgir em uma nova posição.', 'warmup.switch.instruction': 'Mantenha a mira no alvo para confirmar cada troca.', 'warmup.tracking.name': 'Tracking contínuo', 'warmup.tracking.description': 'Acompanhe uma bola em movimento pelo maior tempo possível sem perder o contato.', 'warmup.tracking.instruction': 'Siga o alvo continuamente. Não é necessário clicar.', 'warmup.flick.name': 'Tiro ao alvo', 'warmup.flick.description': 'Atire nas bolas que aparecem em pontos diferentes da arena antes do tempo acabar.', 'warmup.flick.instruction': 'Use o botão esquerdo para acertar cada alvo.',
  'warmup.reflex.name': 'Reflex', 'warmup.reflex.description': 'Acerte o alvo antes que ele desapareça. Cada nível reduz o tempo disponível para reagir.', 'warmup.reflex.instruction': 'Clique no alvo antes que o tempo de reação se esgote.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Três alvos permanecem na arena. Cada acerto substitui um deles em uma nova posição.', 'warmup.gridshot.instruction': 'Alterne rapidamente entre os três alvos e mantenha a precisão.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Acompanhe um alvo em movimento lateral que muda de direção durante o percurso.', 'warmup.strafetrack.instruction': 'Mantenha a mira no alvo durante as mudanças de direção.',
  'difficulty.easy': 'Fácil', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Difícil', 'difficulty.adaptive': 'Adaptativa', 'difficulty.easyDescription': 'Alvo maior e ritmo leve', 'difficulty.mediumDescription': 'Equilíbrio de ritmo e precisão', 'difficulty.hardDescription': 'Alvo menor e resposta rápida', 'difficulty.adaptiveDescription': 'Ajusta o nível após cada rodada',
  'routine.kicker': 'Rotinas FPS', 'routine.title': 'Treine cinco fundamentos em cinco minutos', 'routine.subtitle': 'Presets equilibrados para desenvolver precisão, troca de alvos, tracking e controle fino.', 'routine.configure': 'Configurar rotina', 'routine.phases': '5 fases · 1 minuto cada', 'routine.fundamentalsDescription': 'Base equilibrada de tracking, troca de alvos, precisão e reação.', 'routine.tacticalDescription': 'Controle fino e microcorreções para jogos táticos como CS2 e Valorant.', 'routine.reactiveDescription': 'Tracking suave, mudanças de direção e resposta rápida a novos alvos.', 'routine.phase': 'Fase {current} de {total}', 'routine.phaseComplete': 'Fase concluída', 'routine.nextExercise': 'Próximo exercício: {exercise}', 'routine.complete': 'Rotina concluída', 'routine.totalScore': 'Score total', 'routine.start': 'Iniciar rotina', 'routine.nextPhase': 'Próxima fase', 'routine.repeatPhase': 'Repetir fase', 'routine.setupTitle': 'Configurar {routine}', 'routine.setupDescription': 'Defina jogo, sensibilidade, dificuldade e mira uma única vez para as cinco fases.', 'routine.selectPreset': 'Escolha uma rotina',
  'converter.kicker': 'Conversão 360°', 'converter.title': 'Conversor de sensibilidade', 'converter.subtitle': 'Transfira sua sensibilidade de hipfire mantendo a mesma distância física para completar uma volta de 360°.', 'converter.from': 'Converter de', 'converter.to': 'Converter para', 'converter.currentSensitivity': 'Sensibilidade atual', 'converter.sourceDpi': 'DPI de origem', 'converter.convertedSensitivity': 'Sensibilidade convertida', 'converter.targetDpi': 'DPI de destino', 'converter.swap': 'Inverter jogos', 'converter.copy': 'Copiar sensibilidade convertida', 'converter.nonlinear': 'Este par inclui uma escala não linear. PUBG e Battlefield 6 exigem perfil específico de FOV e configuração para uma conversão confiável.', 'converter.invalidSensitivity': 'Informe uma sensibilidade válida e maior que zero.', 'converter.invalidDpi': 'Informe valores de DPI válidos e maiores que zero.', 'converter.estimated': 'ARC Raiders usa uma equivalência aproximada. Confirme com uma volta de 360° dentro do jogo.', 'converter.sourceRange': 'A sensibilidade informada está fora do intervalo configurável de {game}.', 'converter.targetRange': 'O resultado está fora do intervalo configurável de {game}.', 'converter.linear': 'Conversão linear de hipfire com ajuste de DPI. FOV e ADS podem alterar a sensação visual.',
  'polling.diagnostics': 'Diagnóstico', 'polling.title': 'Teste de polling rate', 'polling.subtitle': 'Meça a frequência com que o navegador recebe atualizações do seu mouse.', 'polling.moveTip': 'Faça movimentos rápidos e circulares durante os 8 segundos.', 'polling.performanceTip': 'Feche programas pesados para reduzir interferências no resultado.', 'polling.rawSupported': 'Entrada bruta suportada neste navegador.', 'polling.compatibleMode': 'Usando modo compatível. Para maior precisão, prefira Chrome ou Edge.', 'polling.measuring': 'MEDINDO AGORA', 'polling.complete': 'TESTE CONCLUÍDO', 'polling.ready': 'PRONTO PARA MEDIR', 'polling.probableHz': 'Hz prováveis', 'polling.observedHz': 'Hz observados', 'polling.samples': '{samples} amostras válidas', 'polling.duration': '{seconds} segundos de teste', 'polling.remaining': '{seconds}s restantes', 'polling.testAgain': 'Testar novamente', 'polling.start': 'Iniciar teste', 'polling.observedPeak': 'Pico observado', 'polling.validSamples': 'Amostras válidas', 'polling.probableRate': 'Polling rate provável', 'polling.disclaimer': 'Resultado estimado pelos eventos entregues ao navegador. Sistema operacional, carga da CPU e agrupamento de eventos podem alterar a medição, especialmente em 4K e 8K.',
  'buttons.diagnostics': 'Diagnóstico de entrada', 'buttons.title': 'Teste de mouse e teclado', 'buttons.subtitle': 'Selecione o dispositivo e pressione uma ou várias entradas ao mesmo tempo para conferir o acionamento.', 'buttons.device': 'Dispositivo para teste', 'buttons.keyboard': 'Teclado', 'buttons.mouseArea': 'Área de teste dos botões do mouse', 'buttons.keyboardArea': 'Área de teste das teclas', 'buttons.pressedNow': 'Pressionado agora', 'buttons.waiting': 'Aguardando entrada', 'buttons.mousePrompt': 'Clique ou role o mouse', 'buttons.keyboardPrompt': 'Pressione qualquer tecla', 'buttons.scrollUp': 'Scroll para cima', 'buttons.scrollDown': 'Scroll para baixo', 'buttons.scrolls': 'Rolagens', 'buttons.coverage': 'COBERTURA', 'buttons.keysTested': 'Teclas testadas', 'buttons.actions': 'ACIONAMENTOS', 'buttons.totalRecorded': 'Total registrado', 'buttons.simultaneous': 'SIMULTÂNEAS', 'buttons.pressedCount': 'Pressionadas agora', 'buttons.reset': 'Zerar contadores', 'mouse.left': 'Esquerdo', 'mouse.middle': 'Scroll', 'mouse.right': 'Direito', 'mouse.back': 'Voltar', 'mouse.forward': 'Avançar', 'key.space': 'Espaço',
}

export type TranslationKey = keyof typeof pt

const en: Record<TranslationKey, string> = {
  ...pt,
  'meta.title': '$ENSI - FPS warm-up, sensitivity and diagnostics',
  'calibration.targetSpeed': 'Target speed',
  'buttons.mouse': 'Mouse',
  'common.stability': 'Stability', 'common.samples': 'Samples',
  'language.selector': 'Page language',
  'nav.routine': 'Routine', 'nav.warmup': 'Warm-up', 'nav.calibration': 'Sensitivity Calibration', 'nav.converter': 'Converter', 'nav.polling': 'Polling Rate', 'nav.buttons': 'Button Test',
  'header.rounds': '{completed}/{total} rounds', 'header.openSettings': 'Open settings', 'header.dailyRoutine': 'Daily routine', 'header.aimTraining': 'Aim training', 'header.conversion': '360° conversion', 'header.inputDiagnostics': 'Input diagnostics', 'header.mouseDiagnostics': 'Mouse diagnostics',
  'common.accuracy': 'Accuracy', 'common.meanError': 'Average error', 'common.smoothness': 'Smoothness', 'common.sensitivity': 'Sensitivity', 'common.time': 'Time', 'common.score': 'Score', 'common.result': 'Result', 'common.restart': 'Restart', 'common.close': 'Close', 'common.mouseDpi': 'Mouse DPI', 'common.gameReference': 'Reference game',
  'calibration.live': 'Live', 'calibration.roundOf': 'Round {round} of {total}', 'calibration.testSensitivity': 'Sensitivity under test', 'calibration.speed': '{speed} speed', 'calibration.prepareHand': 'Get your hand ready. This round is not scoring yet.', 'calibration.warmup': 'The target is already moving. Use this second to settle into the tracking.', 'calibration.guidance': 'Move naturally. The target keeps a fixed speed and changes direction randomly.', 'calibration.trackingActive': 'Tracking active · click the arena if the cursor is released', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pause', 'calibration.resume': 'Resume',
  'calibration.setupTitle': 'Configure before the test', 'calibration.setupDescription': 'Choose a game, enter your current sensitivity, and select the target speed. The test uses {rounds} rounds of {seconds} seconds to calibrate your aim.', 'calibration.currentSensitivity': 'Current sensitivity in {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Fast', 'calibration.fastBadge': 'Fast', 'calibration.normalDescription': 'Balanced speed for standard calibration', 'calibration.fastDescription': 'Faster target for more demanding tracking', 'calibration.crosshairType': 'Crosshair type', 'calibration.baseSensitivity': 'Base sensitivity in {game}', 'calibration.saveStart': 'Save and start test', 'calibration.save': 'Save settings',
  'calibration.landingTitle': 'Find your ideal sensitivity', 'calibration.landingDescription': 'Five tracking rounds analyze your accuracy, average error, and smoothness to find the best balance for your aim.', 'calibration.landingStart': 'Start calibration', 'calibration.landingPreview': 'Tracking demonstration', 'calibration.landingRoundsLabel': 'rounds', 'calibration.landingSecondsLabel': 'seconds each', 'calibration.landingGameResult': 'Result for your game', 'calibration.landingStepConfigure': 'Configure', 'calibration.landingStepConfigureDescription': 'Choose your game, current sensitivity, and mouse DPI.', 'calibration.landingStepTrack': 'Track the target', 'calibration.landingStepTrackDescription': 'Follow the target while we test small sensitivity variations.', 'calibration.landingStepResult': 'Get your result', 'calibration.landingStepResultDescription': 'See only the recommended sensitivity for your selected game.',
  'crosshair.classic': 'Classic', 'crosshair.dot': 'Dot', 'crosshair.circle': 'Circle', 'crosshair.plus': 'Full cross', 'crosshair.classicDescription': 'Thin lines with an open center', 'crosshair.dotDescription': 'Clean center dot', 'crosshair.circleDescription': 'Ring with a center dot', 'crosshair.plusDescription': 'Compact, direct crosshair',
  'calibration.resultTitle': 'Recommended sensitivity', 'calibration.resultDescription': 'Your best balance of accuracy, control, and smoothness appeared at {multiplier}× your initial setting with {speed} speed.', 'calibration.disclaimer': 'Estimate based on this session. Validate the recommendation in the game’s practice range before competing.', 'calibration.redo': 'Run calibration again',
  'arena.currentRound': 'Current round', 'arena.calibrationComplete': 'Calibration complete', 'arena.roundComplete': 'Round complete', 'arena.ready': 'Ready to calibrate', 'arena.fiveRounds': 'All five rounds have been recorded.', 'arena.continueReady': 'Continue when you are ready.', 'arena.startHint': 'Start the test to prepare the first round.', 'arena.viewResult': 'View result', 'arena.nextRound': 'Next round', 'arena.startTest': 'Start test', 'arena.notScoring': 'This round is not scoring yet', 'arena.lockCursor': 'Click to lock the cursor', 'arena.testSensitivity': 'Test sensitivity',
  'warmup.kicker': 'FPS Warm-up', 'warmup.title': 'Get your aim ready before the match', 'warmup.subtitle': 'Choose a 1-minute exercise, adjust the difficulty, and warm up with your in-game sensitivity.', 'warmup.configure': 'Configure exercise', 'warmup.configureExercise': 'Configure {exercise}', 'warmup.sessionDuration': '{description} The session lasts {seconds} seconds.', 'warmup.difficulty': 'Difficulty', 'warmup.crosshair': 'Crosshair', 'warmup.start': 'Start warm-up', 'warmup.complete': 'Warm-up complete', 'warmup.level': 'Level', 'warmup.timeOnTarget': 'Time on target', 'warmup.hits': 'Hits', 'warmup.chooseTraining': 'Choose exercise', 'warmup.repeat': 'Repeat', 'warmup.prepareAim': 'Get your aim ready',
  'warmup.stepGame': 'Game', 'warmup.stepSettings': 'Settings', 'warmup.stepCrosshair': 'Crosshair', 'warmup.chooseGame': 'Choose your game', 'warmup.settingsTitle': 'Tune your sensitivity', 'warmup.crosshairTitle': 'Choose your crosshair', 'warmup.back': 'Back', 'warmup.next': 'Continue', 'warmup.exit': 'Exit', 'warmup.nextRound': 'Next round', 'warmup.nextLevelHint': 'Recommended next level: {level}', 'warmup.keepHardHint': 'Stay on Hard and try to beat your result.', 'warmup.adaptiveNextHint': 'The next round will adjust to {level}.', 'warmup.fixedNextHint': 'The next round will use a new path at {level}.',
  'warmup.switch.name': 'Target switch', 'warmup.switch.description': 'Hold your crosshair on the target until it disappears and reappears in a new position.', 'warmup.switch.instruction': 'Keep your crosshair on the target to confirm each switch.', 'warmup.tracking.name': 'Continuous tracking', 'warmup.tracking.description': 'Follow a moving target for as long as possible without losing contact.', 'warmup.tracking.instruction': 'Track the target continuously. No clicking required.', 'warmup.flick.name': 'Target shooting', 'warmup.flick.description': 'Shoot the targets that appear across the arena before time runs out.', 'warmup.flick.instruction': 'Use the left mouse button to hit each target.',
  'warmup.reflex.name': 'Reflex', 'warmup.reflex.description': 'Hit the target before it disappears. Each level shortens the available reaction time.', 'warmup.reflex.instruction': 'Click the target before the reaction window runs out.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Three targets stay in the arena. Each hit replaces one at a new position.', 'warmup.gridshot.instruction': 'Switch quickly between the three targets while staying accurate.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Track a laterally moving target that changes direction during its path.', 'warmup.strafetrack.instruction': 'Keep your crosshair on the target through every direction change.',
  'difficulty.easy': 'Easy', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Hard', 'difficulty.adaptive': 'Adaptive', 'difficulty.easyDescription': 'Larger target and relaxed pace', 'difficulty.mediumDescription': 'Balanced pace and accuracy', 'difficulty.hardDescription': 'Smaller target and faster response', 'difficulty.adaptiveDescription': 'Adjusts the level after each round',
  'routine.kicker': 'FPS Routines', 'routine.title': 'Train five fundamentals in five minutes', 'routine.subtitle': 'Balanced presets designed to build precision, target switching, tracking, and fine control.', 'routine.configure': 'Configure routine', 'routine.phases': '5 phases · 1 minute each', 'routine.fundamentalsDescription': 'A balanced base of tracking, target switching, precision, and reaction.', 'routine.tacticalDescription': 'Fine control and micro-corrections for tactical games such as CS2 and Valorant.', 'routine.reactiveDescription': 'Smooth tracking, direction changes, and fast responses to new targets.', 'routine.phase': 'Phase {current} of {total}', 'routine.phaseComplete': 'Phase complete', 'routine.nextExercise': 'Next exercise: {exercise}', 'routine.complete': 'Routine complete', 'routine.totalScore': 'Total score', 'routine.start': 'Start routine', 'routine.nextPhase': 'Next phase', 'routine.repeatPhase': 'Repeat phase', 'routine.setupTitle': 'Configure {routine}', 'routine.setupDescription': 'Set your game, sensitivity, difficulty, and crosshair once for all five phases.', 'routine.selectPreset': 'Choose a routine',
  'converter.kicker': '360° Conversion', 'converter.title': 'Sensitivity converter', 'converter.subtitle': 'Transfer your hipfire sensitivity while preserving the same physical distance for a full 360° turn.', 'converter.from': 'Convert from', 'converter.to': 'Convert to', 'converter.currentSensitivity': 'Current sensitivity', 'converter.sourceDpi': 'Source DPI', 'converter.convertedSensitivity': 'Converted sensitivity', 'converter.targetDpi': 'Target DPI', 'converter.swap': 'Swap games', 'converter.copy': 'Copy converted sensitivity', 'converter.nonlinear': 'This pair includes a non-linear scale. PUBG and Battlefield 6 require a specific FOV and settings profile for a reliable conversion.', 'converter.invalidSensitivity': 'Enter a valid sensitivity greater than zero.', 'converter.invalidDpi': 'Enter valid DPI values greater than zero.', 'converter.estimated': 'ARC Raiders uses an approximate equivalence. Confirm it with a 360° turn in-game.', 'converter.sourceRange': 'The entered sensitivity is outside the configurable range for {game}.', 'converter.targetRange': 'The result is outside the configurable range for {game}.', 'converter.linear': 'Linear hipfire conversion with DPI adjustment. FOV and ADS may change the perceived feel.',
  'polling.diagnostics': 'Diagnostics', 'polling.title': 'Polling rate test', 'polling.subtitle': 'Measure how often the browser receives updates from your mouse.', 'polling.moveTip': 'Move the mouse quickly in circles during the 8-second test.', 'polling.performanceTip': 'Close demanding programs to reduce interference in the result.', 'polling.rawSupported': 'Raw input is supported in this browser.', 'polling.compatibleMode': 'Using compatibility mode. For better accuracy, use Chrome or Edge.', 'polling.measuring': 'MEASURING NOW', 'polling.complete': 'TEST COMPLETE', 'polling.ready': 'READY TO MEASURE', 'polling.probableHz': 'Likely Hz', 'polling.observedHz': 'Observed Hz', 'polling.samples': '{samples} valid samples', 'polling.duration': '{seconds}-second test', 'polling.remaining': '{seconds}s remaining', 'polling.testAgain': 'Test again', 'polling.start': 'Start test', 'polling.observedPeak': 'Observed peak', 'polling.validSamples': 'Valid samples', 'polling.probableRate': 'Likely polling rate', 'polling.disclaimer': 'Estimated from events delivered to the browser. The operating system, CPU load, and event coalescing can affect the reading, especially at 4K and 8K.',
  'buttons.diagnostics': 'Input diagnostics', 'buttons.title': 'Mouse and keyboard test', 'buttons.subtitle': 'Select a device and press one or more inputs at the same time to verify activation.', 'buttons.device': 'Device to test', 'buttons.keyboard': 'Keyboard', 'buttons.mouseArea': 'Mouse button test area', 'buttons.keyboardArea': 'Keyboard test area', 'buttons.pressedNow': 'Pressed now', 'buttons.waiting': 'Waiting for input', 'buttons.mousePrompt': 'Click or scroll the mouse', 'buttons.keyboardPrompt': 'Press any key', 'buttons.scrollUp': 'Scroll up', 'buttons.scrollDown': 'Scroll down', 'buttons.scrolls': 'Scrolls', 'buttons.coverage': 'COVERAGE', 'buttons.keysTested': 'Keys tested', 'buttons.actions': 'ACTIVATIONS', 'buttons.totalRecorded': 'Total recorded', 'buttons.simultaneous': 'SIMULTANEOUS', 'buttons.pressedCount': 'Pressed now', 'buttons.reset': 'Reset counters', 'mouse.left': 'Left', 'mouse.middle': 'Wheel', 'mouse.right': 'Right', 'mouse.back': 'Back', 'mouse.forward': 'Forward', 'key.space': 'Space',
}

const es: Record<TranslationKey, string> = {
  ...pt,
  'meta.title': '$ENSI - Calentamiento, sensibilidad y diagnostico FPS',
  'calibration.targetSpeed': 'Velocidad del objetivo',
  'buttons.mouse': 'Ratón',
  'common.stability': 'Estabilidad', 'common.samples': 'Muestras',
  'language.selector': 'Idioma de la página',
  'nav.routine': 'Rutina', 'nav.warmup': 'Calentamiento', 'nav.calibration': 'Calibración de sensibilidad', 'nav.converter': 'Conversor', 'nav.polling': 'Tasa de sondeo', 'nav.buttons': 'Prueba de botones',
  'header.rounds': '{completed}/{total} rondas', 'header.openSettings': 'Abrir configuración', 'header.dailyRoutine': 'Rutina diaria', 'header.aimTraining': 'Entrenamiento de puntería', 'header.conversion': 'Conversión 360°', 'header.inputDiagnostics': 'Diagnóstico de entrada', 'header.mouseDiagnostics': 'Diagnóstico del ratón',
  'common.accuracy': 'Precisión', 'common.meanError': 'Error medio', 'common.smoothness': 'Suavidad', 'common.sensitivity': 'Sensibilidad', 'common.time': 'Tiempo', 'common.score': 'Puntuación', 'common.result': 'Resultado', 'common.restart': 'Reiniciar', 'common.close': 'Cerrar', 'common.mouseDpi': 'DPI del ratón', 'common.gameReference': 'Juego de referencia',
  'calibration.live': 'En vivo', 'calibration.roundOf': 'Ronda {round} de {total}', 'calibration.testSensitivity': 'Sensibilidad en prueba', 'calibration.speed': 'Velocidad {speed}', 'calibration.prepareHand': 'Prepara la mano. La ronda todavía no puntúa.', 'calibration.warmup': 'El objetivo ya está en movimiento. Usa este segundo para ajustar el seguimiento.', 'calibration.guidance': 'Muévete con naturalidad. El objetivo mantiene una velocidad fija y cambia de dirección aleatoriamente.', 'calibration.trackingActive': 'Seguimiento activo · haz clic en la arena si se libera el cursor', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pausar', 'calibration.resume': 'Reanudar',
  'calibration.setupTitle': 'Configurar antes de la prueba', 'calibration.setupDescription': 'Elige el juego, introduce tu sensibilidad actual y selecciona la velocidad del objetivo. La prueba usa {rounds} rondas de {seconds} segundos para calibrar tu puntería.', 'calibration.currentSensitivity': 'Sensibilidad actual en {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Rápido', 'calibration.fastBadge': 'Rápida', 'calibration.normalDescription': 'Velocidad equilibrada para una calibración estándar', 'calibration.fastDescription': 'Objetivo más rápido para un seguimiento más exigente', 'calibration.crosshairType': 'Tipo de mira', 'calibration.baseSensitivity': 'Sensibilidad base en {game}', 'calibration.saveStart': 'Guardar e iniciar prueba', 'calibration.save': 'Guardar configuración',
  'calibration.landingTitle': 'Descubre tu sensibilidad ideal', 'calibration.landingDescription': 'Cinco rondas de tracking analizan tu precisión, error medio y suavidad para encontrar el mejor equilibrio para tu puntería.', 'calibration.landingStart': 'Iniciar calibración', 'calibration.landingPreview': 'Demostración de tracking', 'calibration.landingRoundsLabel': 'rondas', 'calibration.landingSecondsLabel': 'segundos cada una', 'calibration.landingGameResult': 'Resultado para tu juego', 'calibration.landingStepConfigure': 'Configura', 'calibration.landingStepConfigureDescription': 'Elige el juego, tu sensibilidad actual y los DPI del ratón.', 'calibration.landingStepTrack': 'Haz el tracking', 'calibration.landingStepTrackDescription': 'Sigue el objetivo mientras probamos pequeñas variaciones.', 'calibration.landingStepResult': 'Recibe el resultado', 'calibration.landingStepResultDescription': 'Consulta solo la sensibilidad recomendada para el juego elegido.',
  'crosshair.classic': 'Clásica', 'crosshair.dot': 'Punto', 'crosshair.circle': 'Circular', 'crosshair.plus': 'Cruz completa', 'crosshair.classicDescription': 'Líneas finas con el centro abierto', 'crosshair.dotDescription': 'Punto central limpio', 'crosshair.circleDescription': 'Anillo con punto central', 'crosshair.plusDescription': 'Mira compacta y directa',
  'calibration.resultTitle': 'Sensibilidad recomendada', 'calibration.resultDescription': 'Tu mejor equilibrio entre precisión, control y suavidad apareció en {multiplier}× de la configuración inicial con velocidad {speed}.', 'calibration.disclaimer': 'Estimación basada en esta sesión. Valida la recomendación en el campo de práctica del juego antes de competir.', 'calibration.redo': 'Repetir calibración',
  'arena.currentRound': 'Ronda actual', 'arena.calibrationComplete': 'Calibración completada', 'arena.roundComplete': 'Ronda completada', 'arena.ready': 'Todo listo para calibrar', 'arena.fiveRounds': 'Se registraron las cinco rondas.', 'arena.continueReady': 'Continúa cuando estés preparado.', 'arena.startHint': 'Inicia la prueba para preparar la primera ronda.', 'arena.viewResult': 'Ver resultado', 'arena.nextRound': 'Siguiente ronda', 'arena.startTest': 'Iniciar prueba', 'arena.notScoring': 'Esta ronda todavía no puntúa', 'arena.lockCursor': 'Haz clic para bloquear el cursor', 'arena.testSensitivity': 'Sensi en prueba',
  'warmup.kicker': 'Calentamiento FPS', 'warmup.title': 'Prepara tu puntería antes de la partida', 'warmup.subtitle': 'Elige un ejercicio de 1 minuto, ajusta la dificultad y calienta con la sensibilidad de tu juego.', 'warmup.configure': 'Configurar ejercicio', 'warmup.configureExercise': 'Configurar {exercise}', 'warmup.sessionDuration': '{description} La sesión dura {seconds} segundos.', 'warmup.difficulty': 'Dificultad', 'warmup.crosshair': 'Mira', 'warmup.start': 'Iniciar calentamiento', 'warmup.complete': 'Calentamiento completado', 'warmup.level': 'Nivel', 'warmup.timeOnTarget': 'Tiempo en el objetivo', 'warmup.hits': 'Aciertos', 'warmup.chooseTraining': 'Elegir ejercicio', 'warmup.repeat': 'Repetir', 'warmup.prepareAim': 'Prepara la mira',
  'warmup.stepGame': 'Juego', 'warmup.stepSettings': 'Ajustes', 'warmup.stepCrosshair': 'Mira', 'warmup.chooseGame': 'Elige tu juego', 'warmup.settingsTitle': 'Ajusta tu sensibilidad', 'warmup.crosshairTitle': 'Elige tu mira', 'warmup.back': 'Volver', 'warmup.next': 'Continuar', 'warmup.exit': 'Salir', 'warmup.nextRound': 'Siguiente ronda', 'warmup.nextLevelHint': 'Siguiente nivel recomendado: {level}', 'warmup.keepHardHint': 'Continúa en Difícil e intenta superar tu resultado.', 'warmup.adaptiveNextHint': 'La siguiente ronda se ajustará a {level}.', 'warmup.fixedNextHint': 'La siguiente ronda tendrá una nueva trayectoria en {level}.',
  'warmup.switch.name': 'Cambio de objetivo', 'warmup.switch.description': 'Mantén la mira sobre el objetivo hasta que desaparezca y reaparezca en una nueva posición.', 'warmup.switch.instruction': 'Mantén la mira sobre el objetivo para confirmar cada cambio.', 'warmup.tracking.name': 'Seguimiento continuo', 'warmup.tracking.description': 'Sigue un objetivo en movimiento el mayor tiempo posible sin perder el contacto.', 'warmup.tracking.instruction': 'Sigue el objetivo continuamente. No es necesario hacer clic.', 'warmup.flick.name': 'Tiro a objetivos', 'warmup.flick.description': 'Dispara a los objetivos que aparecen por la arena antes de que se acabe el tiempo.', 'warmup.flick.instruction': 'Usa el botón izquierdo para acertar cada objetivo.',
  'warmup.reflex.name': 'Reflejos', 'warmup.reflex.description': 'Acierta el objetivo antes de que desaparezca. Cada nivel reduce el tiempo disponible para reaccionar.', 'warmup.reflex.instruction': 'Haz clic en el objetivo antes de que se agote el tiempo de reacción.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Tres objetivos permanecen en la arena. Cada acierto sustituye uno en una nueva posición.', 'warmup.gridshot.instruction': 'Alterna rápidamente entre los tres objetivos sin perder precisión.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Sigue un objetivo que se mueve lateralmente y cambia de dirección durante el recorrido.', 'warmup.strafetrack.instruction': 'Mantén la mira en el objetivo durante los cambios de dirección.',
  'difficulty.easy': 'Fácil', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Difícil', 'difficulty.adaptive': 'Adaptativa', 'difficulty.easyDescription': 'Objetivo mayor y ritmo suave', 'difficulty.mediumDescription': 'Equilibrio entre ritmo y precisión', 'difficulty.hardDescription': 'Objetivo menor y respuesta rápida', 'difficulty.adaptiveDescription': 'Ajusta el nivel después de cada ronda',
  'routine.kicker': 'Rutinas FPS', 'routine.title': 'Entrena cinco fundamentos en cinco minutos', 'routine.subtitle': 'Presets equilibrados para desarrollar precisión, cambio de objetivos, tracking y control fino.', 'routine.configure': 'Configurar rutina', 'routine.phases': '5 fases · 1 minuto cada una', 'routine.fundamentalsDescription': 'Una base equilibrada de tracking, cambio de objetivos, precisión y reacción.', 'routine.tacticalDescription': 'Control fino y microcorrecciones para juegos tácticos como CS2 y Valorant.', 'routine.reactiveDescription': 'Tracking fluido, cambios de dirección y respuesta rápida a nuevos objetivos.', 'routine.phase': 'Fase {current} de {total}', 'routine.phaseComplete': 'Fase completada', 'routine.nextExercise': 'Siguiente ejercicio: {exercise}', 'routine.complete': 'Rutina completada', 'routine.totalScore': 'Puntuación total', 'routine.start': 'Iniciar rutina', 'routine.nextPhase': 'Siguiente fase', 'routine.repeatPhase': 'Repetir fase', 'routine.setupTitle': 'Configurar {routine}', 'routine.setupDescription': 'Define juego, sensibilidad, dificultad y mira una sola vez para las cinco fases.', 'routine.selectPreset': 'Elige una rutina',
  'converter.kicker': 'Conversión 360°', 'converter.title': 'Conversor de sensibilidad', 'converter.subtitle': 'Transfiere tu sensibilidad de disparo desde la cadera manteniendo la misma distancia física para completar un giro de 360°.', 'converter.from': 'Convertir de', 'converter.to': 'Convertir a', 'converter.currentSensitivity': 'Sensibilidad actual', 'converter.sourceDpi': 'DPI de origen', 'converter.convertedSensitivity': 'Sensibilidad convertida', 'converter.targetDpi': 'DPI de destino', 'converter.swap': 'Intercambiar juegos', 'converter.copy': 'Copiar sensibilidad convertida', 'converter.nonlinear': 'Este par incluye una escala no lineal. PUBG y Battlefield 6 requieren un perfil específico de FOV y configuración para una conversión fiable.', 'converter.invalidSensitivity': 'Introduce una sensibilidad válida mayor que cero.', 'converter.invalidDpi': 'Introduce valores de DPI válidos mayores que cero.', 'converter.estimated': 'ARC Raiders utiliza una equivalencia aproximada. Confírmala con un giro de 360° dentro del juego.', 'converter.sourceRange': 'La sensibilidad introducida está fuera del intervalo configurable de {game}.', 'converter.targetRange': 'El resultado está fuera del intervalo configurable de {game}.', 'converter.linear': 'Conversión lineal de disparo desde la cadera con ajuste de DPI. El FOV y el ADS pueden cambiar la sensación visual.',
  'polling.diagnostics': 'Diagnóstico', 'polling.title': 'Prueba de tasa de sondeo', 'polling.subtitle': 'Mide la frecuencia con la que el navegador recibe actualizaciones del ratón.', 'polling.moveTip': 'Haz movimientos rápidos y circulares durante los 8 segundos.', 'polling.performanceTip': 'Cierra los programas pesados para reducir interferencias en el resultado.', 'polling.rawSupported': 'La entrada sin procesar es compatible con este navegador.', 'polling.compatibleMode': 'Usando el modo compatible. Para obtener mayor precisión, usa Chrome o Edge.', 'polling.measuring': 'MIDIENDO AHORA', 'polling.complete': 'PRUEBA COMPLETADA', 'polling.ready': 'LISTO PARA MEDIR', 'polling.probableHz': 'Hz probables', 'polling.observedHz': 'Hz observados', 'polling.samples': '{samples} muestras válidas', 'polling.duration': '{seconds} segundos de prueba', 'polling.remaining': 'Quedan {seconds}s', 'polling.testAgain': 'Probar de nuevo', 'polling.start': 'Iniciar prueba', 'polling.observedPeak': 'Pico observado', 'polling.validSamples': 'Muestras válidas', 'polling.probableRate': 'Tasa de sondeo probable', 'polling.disclaimer': 'Resultado estimado a partir de los eventos entregados al navegador. El sistema operativo, la carga de la CPU y la agrupación de eventos pueden alterar la medición, especialmente en 4K y 8K.',
  'buttons.diagnostics': 'Diagnóstico de entrada', 'buttons.title': 'Prueba de ratón y teclado', 'buttons.subtitle': 'Selecciona el dispositivo y pulsa una o varias entradas al mismo tiempo para comprobar su activación.', 'buttons.device': 'Dispositivo para probar', 'buttons.keyboard': 'Teclado', 'buttons.mouseArea': 'Área de prueba de los botones del ratón', 'buttons.keyboardArea': 'Área de prueba del teclado', 'buttons.pressedNow': 'Pulsado ahora', 'buttons.waiting': 'Esperando entrada', 'buttons.mousePrompt': 'Haz clic o desplaza la rueda', 'buttons.keyboardPrompt': 'Pulsa cualquier tecla', 'buttons.scrollUp': 'Rueda hacia arriba', 'buttons.scrollDown': 'Rueda hacia abajo', 'buttons.scrolls': 'Desplazamientos', 'buttons.coverage': 'COBERTURA', 'buttons.keysTested': 'Teclas probadas', 'buttons.actions': 'ACTIVACIONES', 'buttons.totalRecorded': 'Total registrado', 'buttons.simultaneous': 'SIMULTÁNEAS', 'buttons.pressedCount': 'Pulsadas ahora', 'buttons.reset': 'Reiniciar contadores', 'mouse.left': 'Izquierdo', 'mouse.middle': 'Rueda', 'mouse.right': 'Derecho', 'mouse.back': 'Atrás', 'mouse.forward': 'Adelante', 'key.space': 'Espacio',
}

const dictionaries = { pt, en, es }
const localeTags: Record<Locale, string> = { pt: 'pt-BR', en: 'en-US', es: 'es-ES' }

function detectLocale(): Locale {
  const saved = localStorage.getItem('sensi-locale')
  if (saved === 'pt' || saved === 'en' || saved === 'es') return saved
  const languages = navigator.languages?.length ? navigator.languages : [navigator.language]
  for (const language of languages) {
    const code = language.toLowerCase().split('-')[0]
    if (code === 'pt' || code === 'en' || code === 'es') return code
  }
  return 'pt'
}

type I18nValue = {
  locale: Locale
  localeTag: string
  setLocale: (locale: Locale) => void
  t: (key: keyof typeof pt, params?: Params) => string
}

const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(detectLocale)
  useEffect(() => {
    document.documentElement.lang = localeTags[locale]
    document.title = dictionaries[locale]['meta.title']
  }, [locale])
  const value = useMemo<I18nValue>(() => ({
    locale,
    localeTag: localeTags[locale],
    setLocale: (next) => { localStorage.setItem('sensi-locale', next); setLocaleState(next) },
    t: (key, params) => {
      let text = dictionaries[locale][key] ?? pt[key] ?? key
      for (const [name, replacement] of Object.entries(params ?? {})) text = text.replaceAll(`{${name}}`, String(replacement))
      return text
    },
  }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

// The hook shares this module with its provider so consumers import one i18n surface.
// eslint-disable-next-line react-refresh/only-export-components
export function useI18n() {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}
