import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'pt' | 'en' | 'es'
type Params = Record<string, string | number>

const pt = {
  'meta.title': '$ENSI - Aquecimento, sensibilidade e diagnostico FPS',
  'calibration.targetSpeed': 'Velocidade da bolinha',
  'buttons.mouse': 'Mouse',
  'common.stability': 'Estabilidade', 'common.samples': 'Amostras',
  'language.selector': 'Idioma da página',
  'nav.routine': 'Rotina', 'nav.warmup': 'Aquecimento', 'nav.calibration': 'Calibração Sensi', 'nav.converter': 'Conversor', 'nav.polling': 'Polling Rate', 'nav.buttons': 'Teste de botões',
  'header.rounds': '{completed}/{total} rodadas', 'header.openSettings': 'Abrir configurações', 'header.dailyRoutine': 'Rotina diária', 'header.aimTraining': 'Treino de mira', 'header.conversion': 'Conversão 360°', 'header.inputDiagnostics': 'Diagnóstico de entrada', 'header.mouseDiagnostics': 'Diagnóstico do mouse',
  'common.accuracy': 'Precisão', 'common.meanError': 'Erro médio', 'common.smoothness': 'Suavidade', 'common.sensitivity': 'Sensibilidade', 'common.time': 'Tempo', 'common.score': 'Score', 'common.result': 'Resultado', 'common.restart': 'Reiniciar', 'common.close': 'Fechar', 'common.mouseDpi': 'DPI do mouse', 'common.gameReference': 'Jogo de referência',
  'calibration.live': 'Ao vivo', 'calibration.roundOf': 'Rodada {round} de {total}', 'calibration.testSensitivity': 'Sensibilidade em teste', 'calibration.speed': 'Velocidade {speed}', 'calibration.prepareHand': 'Prepare a mão. A rodada ainda não pontua.', 'calibration.warmup': 'A bolinha já está em movimento. Use este segundo para encaixar o tracking.', 'calibration.guidance': 'Faça movimentos naturais. Cada sensibilidade testada recebe a mesma trajetória controlada dentro do bloco.', 'calibration.trackingActive': 'Tracking ativo · se soltar, clique na arena', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pausar', 'calibration.resume': 'Retomar',
  'calibration.setupTitle': 'Configurar antes do teste', 'calibration.setupDescription': 'Escolha o jogo, informe sua sensibilidade atual e selecione a velocidade do alvo. A sessão usa até {rounds} rodadas de {seconds} segundos, incluindo duas comparações finais entre os dois melhores valores.', 'calibration.currentSensitivity': 'Sensibilidade atual no {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Rápido', 'calibration.fastBadge': 'Rápida', 'calibration.normalDescription': 'Velocidade equilibrada para calibração padrão', 'calibration.fastDescription': 'Bolinha mais rápida para tracking mais exigente', 'calibration.crosshairType': 'Tipo de mira', 'calibration.baseSensitivity': 'Sensibilidade base em {game}', 'calibration.saveStart': 'Salvar e iniciar teste', 'calibration.save': 'Salvar configuração',
  'calibration.landingTitle': 'Encontre uma faixa consistente de sensibilidade', 'calibration.landingDescription': 'Medições repetidas com trajetórias equivalentes comparam pequenas variações e informam quando os dados sustentam um valor, uma faixa ou nenhum resultado conclusivo.', 'calibration.landingStart': 'Iniciar calibração', 'calibration.landingPreview': 'Demonstração do tracking', 'calibration.landingRoundsLabel': 'rodadas máximas', 'calibration.landingSecondsLabel': 'segundos cada', 'calibration.landingStepConfigure': 'Configure', 'calibration.landingStepConfigureDescription': 'Escolha o jogo, sua sensibilidade atual e a velocidade do alvo.', 'calibration.landingStepTrack': 'Faça o tracking', 'calibration.landingStepTrackDescription': 'Acompanhe o alvo enquanto testamos pequenas variações.', 'calibration.landingStepResult': 'Receba o resultado', 'calibration.landingStepResultDescription': 'Receba um valor confirmado, uma faixa sugerida ou um resultado inconclusivo.',
  'crosshair.classic': 'Clássica', 'crosshair.dot': 'Bolinha', 'crosshair.circle': 'Circular', 'crosshair.plus': 'Cruz cheia', 'crosshair.classicDescription': 'Linhas finas com centro aberto', 'crosshair.dotDescription': 'Ponto central limpo', 'crosshair.circleDescription': 'Anel com ponto central', 'crosshair.plusDescription': 'Mira compacta e direta',
  'calibration.resultTitle': 'Sensibilidade recomendada', 'calibration.resultDescription': 'Seu melhor equilíbrio entre precisão, controle e suavidade apareceu em {multiplier}× da configuração inicial com velocidade {speed}.', 'calibration.disclaimer': 'Estimativa baseada nesta sessão. Valide a recomendação no campo de treino do jogo antes de competir.', 'calibration.redo': 'Recomeçar calibração', 'calibration.refine': 'Fazer refinamento final',
  'calibration.fromBaseSensitivity': 'a partir da sensi base {sensitivity}', 'calibration.confidence': 'Confiança da sessão', 'calibration.confidenceHigh': 'Alta', 'calibration.confidenceMedium': 'Moderada', 'calibration.confidenceExploratory': 'Exploratória', 'calibration.whyTitle': 'Como interpretar este resultado', 'calibration.technicalConclusion': 'O melhor resultado isolado apareceu em {best}×. Para reduzir o efeito de sorte de uma única rodada, o cálculo combinou os {count} valores mais competitivos entre {min}× e {max}×, dando mais peso às maiores notas. Essa média ponderada chegou a {multiplier}×.', 'calibration.vsBase': 'vs. sensi base', 'calibration.overshoots': 'Overshoots', 'calibration.errorMap': 'Mapa de erro relativo ao alvo', 'calibration.errorMapLegend': 'Centro = alvo · verde dentro · vermelho fora', 'calibration.aimBias': 'Tendência média da mira', 'calibration.biasCentered': 'Centralizada', 'calibration.biasRight': 'À direita', 'calibration.biasLeft': 'À esquerda', 'calibration.biasUp': 'Acima', 'calibration.biasDown': 'Abaixo', 'calibration.howCalculated': 'Como a nota é calculada', 'calibration.errorControl': 'Controle do erro médio', 'calibration.overshootPenalty': 'Penalidade por overshoots', 'calibration.formulaExplanation': 'Precisão mede o tempo dentro do alvo. Controle transforma a distância média em nota. Suavidade avalia variações bruscas na velocidade da mira. Overshoots descontam pontos quando a mira atravessa o alvo e se afasta rapidamente.', 'calibration.confidenceExplanation': 'A confiança considera a qualidade da melhor nota, a proximidade entre as sensibilidades competitivas e a conclusão das cinco rodadas.', 'calibration.candidateEvidence': 'Resultados dos valores testados', 'calibration.competitiveHint': 'Linhas verdes participaram da média final', 'calibration.previousSession': 'Comparação com a calibração anterior', 'calibration.firstSession': 'Esta é a primeira calibração registrada para este jogo.',
  'calibration.adjust': 'AJUSTE', 'calibration.measurementStage': 'Medição', 'calibration.validationStage': 'Validação', 'calibration.validationReady': 'Medições concluídas', 'calibration.validationHint': 'Agora os dois melhores valores serão comparados em duas trajetórias inéditas.', 'calibration.retryRound': 'A rodada não entrou no cálculo. Repita nas mesmas condições.',
  'calibration.issueInsufficientSamples': 'Rodada rejeitada por amostras insuficientes', 'calibration.issueCanvasResized': 'Rodada rejeitada porque a arena mudou de tamanho', 'calibration.issueUnstableFrames': 'Rodada rejeitada por instabilidade excessiva de frames', 'calibration.issueInterruptions': 'Rodada rejeitada porque o cursor foi interrompido durante a medição',
  'calibration.resultTitleRecommended': 'Sensibilidade confirmada', 'calibration.resultTitleRange': 'Ponto inicial e zona de ajuste', 'calibration.resultTitleInconclusive': 'Referência provisória',
  'calibration.reasonConfirmed': 'A validação confirmou o valor mais forte com consistência suficiente.', 'calibration.reasonCloseCandidates': 'Os valores mais fortes ficaram próximos demais para justificar uma única sensibilidade.', 'calibration.reasonLowConsistency': 'As repetições variaram demais para sustentar uma recomendação confiável.', 'calibration.reasonLowSignal': 'O desempenho da sessão não produziu sinal suficiente para diferenciar as sensibilidades.', 'calibration.reasonIncomplete': 'A sessão não reuniu todas as rodadas válidas necessárias.', 'calibration.reasonValidationReversed': 'As duas trajetórias finais favoreceram o outro valor testado.',
  'calibration.rangeFromBase': 'faixa entre {min}× e {max}× da sensibilidade base', 'calibration.technicalConclusionV2': 'O relatório combinou {rounds} rodadas válidas, {values} sensibilidades testadas, repetibilidade de {repeatability}% e concordância de validação de {validation}%. A faixa exibida ficou entre {min}× e {max}×.',
  'calibration.repeatability': 'Repetibilidade', 'calibration.repeatabilityHint': 'Proximidade entre as duas medições de cada sensibilidade', 'calibration.validationAgreement': 'Confirmação final', 'calibration.validationAgreementHint': 'Concordância nas duas trajetórias finais',
  'calibration.formulaExplanationV2': 'A precisão mede o tempo dentro do alvo. O controle transforma o erro médio em nota. A suavidade usa uma medida robusta das mudanças de velocidade. Overshoots descontam pontos.', 'calibration.confidenceExplanationV2': 'A confiança combina qualidade das amostras, repetibilidade, concordância entre blocos, separação dos valores testados e validação final. Ela representa esta sessão, sem garantia de desempenho no jogo.',
  'calibration.testedValuesEvidence': 'Comparação dos valores testados', 'calibration.competitiveHintV2': 'Cada sensibilidade possui duas medições; os dois melhores valores recebem duas comparações finais', 'calibration.sampleQuality': 'Qualidade das amostras', 'calibration.blockAgreement': 'Concordância entre blocos', 'calibration.separation': 'Separação dos valores', 'calibration.completedRounds': 'Rodadas válidas',
  'calibration.disclaimerV2': 'Estimativa experimental baseada nesta sessão e neste exercício de tracking. FOV, ADS, arma, fadiga e mecânicas do jogo podem alterar a preferência. Confirme a faixa no campo de treino e repita a calibração em outro dia antes de adotar uma mudança grande.', 'calibration.insufficientCandidates': 'A precisão configurável deste jogo gera menos de três sensibilidades distintas dentro de ±35%. Use uma sensibilidade base maior ou teste diretamente no jogo.', 'calibration.relativeMethod': 'Teste relativo · DPI não altera a comparação',
  'arena.currentRound': 'Rodada atual', 'arena.calibrationComplete': 'Calibração concluída', 'arena.roundComplete': 'Rodada concluída', 'arena.ready': 'Tudo pronto para calibrar', 'arena.fiveRounds': 'Todas as rodadas foram registradas.', 'arena.allRounds': 'Todas as rodadas válidas foram registradas.', 'arena.continueReady': 'Continue quando estiver preparado.', 'arena.startHint': 'Inicie o teste para preparar a primeira rodada.', 'arena.viewResult': 'Ver resultado', 'arena.nextRound': 'Próxima rodada', 'arena.startTest': 'Iniciar teste', 'arena.notScoring': 'A rodada ainda não está pontuando', 'arena.lockCursor': 'Clique para travar o cursor', 'arena.testSensitivity': 'Sensi em teste',
  'warmup.kicker': 'Aquecimento FPS', 'warmup.title': 'Prepare a mira antes da partida', 'warmup.subtitle': 'Escolha um exercício de 1 minuto, ajuste a dificuldade e entre no ritmo com a sensibilidade do seu jogo.', 'warmup.configure': 'Configurar treino', 'warmup.configureExercise': 'Configurar {exercise}', 'warmup.sessionDuration': '{description} A sessão dura {seconds} segundos.', 'warmup.difficulty': 'Dificuldade', 'warmup.crosshair': 'Mira', 'warmup.start': 'Iniciar aquecimento', 'warmup.complete': 'Aquecimento concluído', 'warmup.level': 'Nível', 'warmup.timeOnTarget': 'Tempo no alvo', 'warmup.hits': 'Acertos', 'warmup.chooseTraining': 'Escolher treino', 'warmup.repeat': 'Repetir', 'warmup.prepareAim': 'Prepare a mira',
  'warmup.stepGame': 'Jogo', 'warmup.stepSettings': 'Ajustes', 'warmup.stepCrosshair': 'Mira', 'warmup.chooseGame': 'Escolha seu jogo', 'warmup.settingsTitle': 'Ajuste sua sensibilidade', 'warmup.crosshairTitle': 'Escolha sua mira', 'warmup.back': 'Voltar', 'warmup.next': 'Continuar', 'warmup.exit': 'Sair', 'warmup.nextRound': 'Próxima rodada', 'warmup.nextLevelHint': 'Próximo nível recomendado: {level}', 'warmup.keepHardHint': 'Continue no nível Difícil e tente superar seu resultado.', 'warmup.adaptiveNextHint': 'A próxima rodada será ajustada automaticamente com base no seu desempenho.', 'warmup.fixedNextHint': 'A próxima rodada terá uma nova trajetória no nível {level}.',
  'warmup.reportTitle': 'Relatório pós-treino', 'warmup.reactionSpeed': 'Velocidade de reação', 'warmup.clickErrors': 'Erros de clique', 'warmup.bestStreak': 'Melhor sequência', 'warmup.aimHeatmap': 'Heatmap da mira', 'warmup.heatmapDescription': 'Concentração em verde; erros e cliques falhos em vermelho.', 'warmup.noHeatmapData': 'Complete uma rodada para gerar o mapa.', 'warmup.overshootDirection': 'Direção predominante dos overshoots', 'warmup.overshootBalanced': 'Centro equilibrado', 'warmup.overshootRight': 'Direita', 'warmup.overshootLeft': 'Esquerda', 'warmup.overshootUp': 'Acima', 'warmup.overshootDown': 'Abaixo', 'warmup.previousComparison': 'Comparação com a sessão anterior', 'warmup.firstComparison': 'Esta é a primeira sessão registrada neste exercício.', 'warmup.nextRecommendation': 'Próximo exercício recomendado', 'warmup.recommendationDescription': 'Sugestão baseada na métrica que mais limitou esta sessão.',
  'warmup.switch.name': 'Troca de alvo', 'warmup.switch.description': 'Segure a mira sobre a bola até ela desaparecer e surgir em uma nova posição.', 'warmup.switch.instruction': 'Mantenha a mira no alvo para confirmar cada troca.', 'warmup.tracking.name': 'Tracking contínuo', 'warmup.tracking.description': 'Acompanhe uma bola em movimento pelo maior tempo possível sem perder o contato.', 'warmup.tracking.instruction': 'Siga o alvo continuamente. Não é necessário clicar.', 'warmup.flick.name': 'Tiro ao alvo', 'warmup.flick.description': 'Atire nas bolas que aparecem em pontos diferentes da arena antes do tempo acabar.', 'warmup.flick.instruction': 'Use o botão esquerdo para acertar cada alvo.',
  'warmup.reflex.name': 'Reflex', 'warmup.reflex.description': 'Acerte o alvo antes que ele desapareça. Cada nível reduz o tempo disponível para reagir.', 'warmup.reflex.instruction': 'Clique no alvo antes que o tempo de reação se esgote.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Três alvos permanecem na arena. Cada acerto substitui um deles em uma nova posição.', 'warmup.gridshot.instruction': 'Alterne rapidamente entre os três alvos e mantenha a precisão.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Acompanhe um alvo em movimento lateral que muda de direção durante o percurso.', 'warmup.strafetrack.instruction': 'Mantenha a mira no alvo durante as mudanças de direção.',
  'difficulty.easy': 'Fácil', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Difícil', 'difficulty.adaptive': 'Adaptativa', 'difficulty.easyDescription': 'Alvo maior e ritmo leve', 'difficulty.mediumDescription': 'Equilíbrio de ritmo e precisão', 'difficulty.hardDescription': 'Alvo menor e resposta rápida', 'difficulty.adaptiveDescription': 'Perfil equilibrado sem progressão automática entre rodadas',
  'routine.kicker': 'Rotinas FPS', 'routine.title': 'Treine cinco fundamentos em cinco minutos', 'routine.subtitle': 'Presets equilibrados para desenvolver precisão, troca de alvos, tracking e controle fino.', 'routine.configure': 'Configurar rotina', 'routine.phases': '5 fases · 1 minuto cada', 'routine.fundamentalsDescription': 'Base equilibrada de tracking, troca de alvos, precisão e reação.', 'routine.tacticalDescription': 'Controle fino e microcorreções para jogos táticos como CS2 e Valorant.', 'routine.reactiveDescription': 'Tracking suave, mudanças de direção e resposta rápida a novos alvos.', 'routine.phase': 'Fase {current} de {total}', 'routine.phaseComplete': 'Fase concluída', 'routine.nextExercise': 'Próximo exercício: {exercise}', 'routine.complete': 'Rotina concluída', 'routine.totalScore': 'Score total', 'routine.start': 'Iniciar rotina', 'routine.nextPhase': 'Próxima fase', 'routine.repeatPhase': 'Repetir fase', 'routine.setupTitle': 'Configurar {routine}', 'routine.setupDescription': 'Defina jogo, sensibilidade, dificuldade e mira uma única vez para as cinco fases.', 'routine.selectPreset': 'Escolha uma rotina',
  'converter.kicker': 'Conversão 360°', 'converter.title': 'Conversor de sensibilidade', 'converter.subtitle': 'Transfira sua sensibilidade de hipfire mantendo a mesma distância física para completar uma volta de 360°.', 'converter.from': 'Converter de', 'converter.to': 'Converter para', 'converter.currentSensitivity': 'Sensibilidade atual', 'converter.sourceDpi': 'DPI de origem', 'converter.convertedSensitivity': 'Sensibilidade convertida', 'converter.targetDpi': 'DPI de destino', 'converter.swap': 'Inverter jogos', 'converter.copy': 'Copiar sensibilidade convertida', 'converter.nonlinear': 'Este par inclui uma escala não linear. PUBG e Battlefield 6 exigem perfil específico de FOV e configuração para uma conversão confiável.', 'converter.invalidSensitivity': 'Informe uma sensibilidade válida e maior que zero.', 'converter.invalidDpi': 'Informe valores de DPI válidos e maiores que zero.', 'converter.estimated': 'ARC Raiders usa uma equivalência aproximada. Confirme com uma volta de 360° dentro do jogo.', 'converter.sourceRange': 'A sensibilidade informada está fora do intervalo configurável de {game}.', 'converter.targetRange': 'O resultado está fora do intervalo configurável de {game}.', 'converter.linear': 'Conversão linear de hipfire com ajuste de DPI. FOV e ADS podem alterar a sensação visual.',
  'polling.diagnostics': 'Diagnóstico', 'polling.title': 'Teste de polling rate', 'polling.subtitle': 'Meça a frequência com que o navegador recebe atualizações do seu mouse.', 'polling.moveTip': 'Faça movimentos rápidos e circulares durante os 8 segundos.', 'polling.performanceTip': 'Feche programas pesados para reduzir interferências no resultado.', 'polling.rawSupported': 'Entrada bruta suportada neste navegador.', 'polling.compatibleMode': 'Usando modo compatível. Para maior precisão, prefira Chrome ou Edge.', 'polling.measuring': 'MEDINDO AGORA', 'polling.complete': 'TESTE CONCLUÍDO', 'polling.ready': 'PRONTO PARA MEDIR', 'polling.probableHz': 'Hz prováveis', 'polling.observedHz': 'Hz observados', 'polling.samples': '{samples} amostras válidas', 'polling.duration': '{seconds} segundos de teste', 'polling.remaining': '{seconds}s restantes', 'polling.testAgain': 'Testar novamente', 'polling.start': 'Iniciar teste', 'polling.observedPeak': 'Pico observado', 'polling.validSamples': 'Amostras válidas', 'polling.probableRate': 'Polling rate provável', 'polling.disclaimer': 'Resultado estimado pelos eventos entregues ao navegador. Sistema operacional, carga da CPU e agrupamento de eventos podem alterar a medição, especialmente em 4K e 8K.',
  'buttons.diagnostics': 'Diagnóstico de entrada', 'buttons.title': 'Teste de mouse e teclado', 'buttons.subtitle': 'Selecione o dispositivo e pressione uma ou várias entradas ao mesmo tempo para conferir o acionamento.', 'buttons.device': 'Dispositivo para teste', 'buttons.keyboard': 'Teclado', 'buttons.mouseArea': 'Área de teste dos botões do mouse', 'buttons.keyboardArea': 'Área de teste das teclas', 'buttons.pressedNow': 'Pressionado agora', 'buttons.waiting': 'Aguardando entrada', 'buttons.mousePrompt': 'Clique ou role o mouse', 'buttons.keyboardPrompt': 'Pressione qualquer tecla', 'buttons.scrollUp': 'Scroll para cima', 'buttons.scrollDown': 'Scroll para baixo', 'buttons.scrolls': 'Rolagens', 'buttons.coverage': 'COBERTURA', 'buttons.keysTested': 'Teclas testadas', 'buttons.actions': 'ACIONAMENTOS', 'buttons.totalRecorded': 'Total registrado', 'buttons.simultaneous': 'SIMULTÂNEAS', 'buttons.pressedCount': 'Pressionadas agora', 'buttons.reset': 'Zerar contadores', 'mouse.left': 'Esquerdo', 'mouse.middle': 'Scroll', 'mouse.right': 'Direito', 'mouse.back': 'Voltar', 'mouse.forward': 'Avançar', 'key.space': 'Espaço',

  'calibration.reasonSplitCandidates': 'Os melhores valores apareceram em pontos separados e não formaram uma faixa contínua.',
  'calibration.confirmedValue': 'Valor confirmado', 'calibration.startingPoint': 'Ponto inicial recomendado', 'calibration.bestObserved': 'Melhor valor observado', 'calibration.recommendationStrength': 'Força da recomendação',
  'calibration.directionLower': 'Redução de {percent}% em relação à base {base}', 'calibration.directionHigher': 'Aumento de {percent}% em relação à base {base}', 'calibration.directionNearBase': 'Resultado próximo da sensibilidade base {base}',
  'calibration.whatToDoNow': 'O que fazer agora', 'calibration.directionIndicated': 'Direção indicada', 'calibration.adjustmentZone': 'Zona de ajuste', 'calibration.refinementRequired': 'Refinamento necessário', 'calibration.zoneHint': 'Região contínua com desempenho equivalente', 'calibration.singlePointHint': 'Um único valor sustentou a melhor evidência da sessão', 'calibration.noContinuousZoneHint': 'A sessão não encontrou uma zona contínua confiável', 'calibration.nextTest': 'Próximo teste', 'calibration.nextTestHint': 'Compare estes três valores em uma etapa curta de refinamento', 'calibration.finalValidation': 'Validação final',
  'calibration.validationUnavailable': 'A sessão ainda não possui validação final.',
  'calibration.conclusionConfirmed': 'A sensibilidade {best} teve a maior nota, {bestScore}, e superou o segundo valor por {gap} pontos. As duas trajetórias finais mantiveram esse resultado. Este foi o ponto mais sustentado da sessão.',
  'calibration.conclusionRange': 'Os melhores resultados formaram uma região contínua entre {zoneMin} e {zoneMax}. O valor {best} teve a maior nota, {bestScore}, enquanto {second} ficou próximo com {secondScore}. Comece no valor destacado e use a zona somente para ajustes pequenos.',
  'calibration.conclusionSplit': 'O melhor resultado isolado foi {best}, com nota {bestScore}, mas {second} também ficou próximo, com {secondScore}. Um valor intermediário mais fraco separa os dois, portanto os dados não formam uma faixa contínua. Use {best} como referência provisória e faça apenas o refinamento final.',
  'calibration.conclusionValidationReversed': 'As medições iniciais favoreceram {best}, porém {validationWinner} venceu as duas trajetórias finais. A referência inicial foi revertida e não deve ser aplicada como recomendação. Repita a calibração completa em outro dia.',
  'calibration.conclusionLowConsistency': 'As repetições variaram mais do que o aceitável. A consistência combinada ficou em {repeatability}% e a concordância entre blocos em {blockAgreement}%. O valor {best} foi o melhor observado, porém ainda não deve substituir sua configuração atual sem refinamento.',
  'calibration.conclusionIncomplete': 'A coleta não reuniu todas as rodadas válidas. O valor {best} aparece apenas como referência do material disponível e não representa uma recomendação concluída.',
  'calibration.conclusionLowSignal': 'As notas ficaram próximas demais ou baixas demais para distinguir uma região estável. O melhor valor observado foi {best}, com nota {bestScore}, apenas {gap} ponto acima da segunda colocada.',
  'calibration.scoreGapHint': 'Vantagem de {gap} ponto sobre a segunda colocada', 'calibration.playerConsistency': 'Consistência do jogador', 'calibration.playerConsistencyHint': 'Repetição do desempenho entre blocos e sensibilidades',
  'calibration.strengthExplanation': 'A força da recomendação considera separação entre valores, consistência, concordância entre blocos e validação. Uma coleta excelente pode produzir uma recomendação fraca quando os resultados se contradizem.', 'calibration.testedValuesHint': 'O destaque marca o melhor resultado observado. Somente valores vizinhos podem formar uma zona de ajuste.',
  'calibration.collectionQuality': 'Qualidade da coleta', 'calibration.collectionQualityHint': 'Amostras, estabilidade e conclusão das rodadas', 'calibration.recommendationStrengthHint': 'Clareza com que os dados sustentam a direção indicada', 'calibration.completedRoundsHint': 'Rodadas aceitas pelo controle de qualidade',
  'calibration.disclaimerV3': 'Estimativa experimental desta sessão de tracking. O ponto destacado foi realmente testado. A zona de ajuste só aparece quando sensibilidades adjacentes tiveram desempenho equivalente. FOV, ADS, arma, fadiga e mecânicas do jogo podem alterar a preferência. Confirme o valor no campo de treino antes de adotar uma mudança permanente.',
  'calibration.reasonValidationSplit': 'A comparação final ficou dividida e não confirmou um único ponto.',
  'calibration.conclusionValidationSplit': 'A comparação final terminou dividida entre os dois valores. O resultado {validationRecord} não confirmou um ponto único. Use {best} somente como referência provisória ou repita a calibração completa em outro dia.',
  'calibration.validationStatusConfirmed': 'Confirmada',
  'calibration.validationStatusSplit': 'Comparação dividida',
  'calibration.validationStatusReversed': 'Resultado revertido',
  'calibration.validationStatusUnavailable': 'Não realizada',
  'calibration.validationConfirmedCount': '{confirmed} de {total} blocos finais favoreceram {value}.',
  'calibration.validationSplitCount': 'A disputa ficou em {confirmed}–{alternative}, com {ties} empate(s). {value} teve a maior média final por {gap} ponto(s).',
  'calibration.validationReversedCount': '{value} venceu {alternative} de {total} trajetórias finais e reverteu o resultado inicial.',
  'calibration.refinementStatus': 'Etapa de refinamento',
  'calibration.refinementCompleted': 'Refinamento final concluído',
  'calibration.refinementCompletedHint': 'O processo foi encerrado para evitar refinamentos sucessivos e falsa precisão.',
  'calibration.refinementNotNeeded': 'Refinamento dispensado',
  'calibration.refinementNotNeededHint': 'Os dados já sustentam uma conclusão prática ou pedem uma nova sessão completa.',
  'calibration.validationColumn': 'Validação',
  'calibration.refineFinal': 'Fazer refinamento final',
  'calibration.finish': 'Usar este resultado',
  'calibration.validationTieShort': 'empate',
  'calibration.validationSplitTieCount': 'A comparação terminou {confirmed}–{alternative}, com {ties} empate(s). A média final ficou dentro da margem técnica de igualdade.',
  'calibration.closeReport': 'Fechar relatório',
  'calibration.roundCountCompact': '{measurements} medições · {validation} finais',
  'calibration.horizontalFov': 'FOV horizontal', 'calibration.cmPer360': 'Distância para 360°', 'calibration.cmPer360Unavailable': 'Perfil físico indisponível',
  'calibration.historyTitle': 'Histórico de calibração', 'calibration.historyCount': '{count} sessões salvas', 'calibration.historyEmpty': 'Conclua uma calibração válida para iniciar o histórico deste jogo.', 'calibration.historyPhysicalAverage': 'Média física das sessões: {value} cm/360°. O histórico informa estabilidade, mas não altera o cálculo da sessão atual.',
  'converter.cmPer360': 'Distância para 360°',
  'calibration.vsBaseClear': 'em relação à sensibilidade base', 'calibration.formulaExplanationPhysical': 'A precisão mede o tempo dentro do alvo. O controle transforma o erro médio em nota. A suavidade usa uma medida robusta das mudanças de velocidade. Ultrapassagens do alvo descontam pontos.',
  'calibration.setupDescriptionPhysical': 'Escolha o jogo, informe sua sensibilidade, DPI e FOV horizontal. A sessão usa até {rounds} rodadas de {seconds} segundos, incluindo duas comparações finais entre os dois valores mais fortes.',
  'calibration.physicalProfile': 'Perfil físico · {dpi} DPI · FOV horizontal {fov}°', 'calibration.relativeProfileNotice': 'Este jogo ainda não possui uma escala linear confirmada no $ENSI. A calibração continua relativa e não exibe cm/360°.',
  'nav.gamepad': 'Controle', 'gamepad.diagnostics': 'Diagnóstico de controle', 'gamepad.title': 'Teste de joystick', 'gamepad.subtitle': 'Leitura em tempo real de botões, analógicos, gatilhos e estabilidade do seu controle.', 'gamepad.waitingTitle': 'Conecte e ative o controle', 'gamepad.waitingDescription': 'Pressione qualquer botão no controle para que o navegador detecte o dispositivo.', 'gamepad.connectedControllers': 'Controles conectados', 'gamepad.controller': 'Controle', 'gamepad.unknown': 'Controle desconhecido', 'gamepad.index': 'Índice', 'gamepad.timestamp': 'Timestamp', 'gamepad.status': 'Status', 'gamepad.connected': 'Conectado', 'gamepad.rumble': 'Testar vibração', 'gamepad.pressed': 'Botões pressionados', 'gamepad.leftStick': 'Analógico esquerdo', 'gamepad.rightStick': 'Analógico direito', 'gamepad.circularity': 'Erro de circularidade', 'gamepad.rawAxes': 'Valores brutos dos eixos', 'gamepad.resetPath': 'Limpar trajetos',

}

export type TranslationKey = keyof typeof pt

const en: Record<TranslationKey, string> = {
  ...pt,
  'meta.title': '$ENSI - FPS warm-up, sensitivity and diagnostics',
  'calibration.targetSpeed': 'Target speed',
  'buttons.mouse': 'Mouse',
  'common.stability': 'Stability', 'common.samples': 'Samples',
  'language.selector': 'Page language',
  'nav.routine': 'Routine', 'nav.warmup': 'Warm-up', 'nav.calibration': 'Sensitivity Calibration', 'nav.converter': 'Converter', 'nav.polling': 'Polling Rate', 'nav.buttons': 'Button Test',
  'header.rounds': '{completed}/{total} rounds', 'header.openSettings': 'Open settings', 'header.dailyRoutine': 'Daily routine', 'header.aimTraining': 'Aim training', 'header.conversion': '360° conversion', 'header.inputDiagnostics': 'Input diagnostics', 'header.mouseDiagnostics': 'Mouse diagnostics',
  'common.accuracy': 'Accuracy', 'common.meanError': 'Average error', 'common.smoothness': 'Smoothness', 'common.sensitivity': 'Sensitivity', 'common.time': 'Time', 'common.score': 'Score', 'common.result': 'Result', 'common.restart': 'Restart', 'common.close': 'Close', 'common.mouseDpi': 'Mouse DPI', 'common.gameReference': 'Reference game',
  'calibration.live': 'Live', 'calibration.roundOf': 'Round {round} of {total}', 'calibration.testSensitivity': 'Sensitivity under test', 'calibration.speed': '{speed} speed', 'calibration.prepareHand': 'Get your hand ready. This round is not scoring yet.', 'calibration.warmup': 'The target is already moving. Use this second to settle into the tracking.', 'calibration.guidance': 'Move naturally. Every tested sensitivity receives the same controlled trajectory within each block.', 'calibration.trackingActive': 'Tracking active · click the arena if the cursor is released', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pause', 'calibration.resume': 'Resume',
  'calibration.setupTitle': 'Configure before the test', 'calibration.setupDescription': 'Choose a game, enter your current sensitivity, and select the target speed. The session uses up to {rounds} rounds of {seconds} seconds, including two final comparisons between the two strongest values.', 'calibration.currentSensitivity': 'Current sensitivity in {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Fast', 'calibration.fastBadge': 'Fast', 'calibration.normalDescription': 'Balanced speed for standard calibration', 'calibration.fastDescription': 'Faster target for more demanding tracking', 'calibration.crosshairType': 'Crosshair type', 'calibration.baseSensitivity': 'Base sensitivity in {game}', 'calibration.saveStart': 'Save and start test', 'calibration.save': 'Save settings',
  'calibration.landingTitle': 'Find a consistent sensitivity range', 'calibration.landingDescription': 'Repeated measurements with equivalent trajectories compare small variations and report when the data supports one value, a range, or no conclusive result.', 'calibration.landingStart': 'Start calibration', 'calibration.landingPreview': 'Tracking demonstration', 'calibration.landingRoundsLabel': 'maximum rounds', 'calibration.landingSecondsLabel': 'seconds each', 'calibration.landingStepConfigure': 'Configure', 'calibration.landingStepConfigureDescription': 'Choose your game, current sensitivity, and target speed.', 'calibration.landingStepTrack': 'Track the target', 'calibration.landingStepTrackDescription': 'Follow the target while we test small sensitivity variations.', 'calibration.landingStepResult': 'Get your result', 'calibration.landingStepResultDescription': 'Receive a confirmed value, a suggested range, or an inconclusive result.',
  'crosshair.classic': 'Classic', 'crosshair.dot': 'Dot', 'crosshair.circle': 'Circle', 'crosshair.plus': 'Full cross', 'crosshair.classicDescription': 'Thin lines with an open center', 'crosshair.dotDescription': 'Clean center dot', 'crosshair.circleDescription': 'Ring with a center dot', 'crosshair.plusDescription': 'Compact, direct crosshair',
  'calibration.resultTitle': 'Recommended sensitivity', 'calibration.resultDescription': 'Your best balance of accuracy, control, and smoothness appeared at {multiplier}× your initial setting with {speed} speed.', 'calibration.disclaimer': 'Estimate based on this session. Validate the recommendation in the game’s practice range before competing.', 'calibration.redo': 'Restart calibration', 'calibration.refine': 'Run final refinement',
  'calibration.fromBaseSensitivity': 'from base sensitivity {sensitivity}', 'calibration.confidence': 'Session confidence', 'calibration.confidenceHigh': 'High', 'calibration.confidenceMedium': 'Moderate', 'calibration.confidenceExploratory': 'Exploratory', 'calibration.whyTitle': 'How to interpret this result', 'calibration.technicalConclusion': 'The strongest individual result appeared at {best}×. To reduce the effect of luck in one round, the calculation combined the {count} strongest tested values between {min}× and {max}×, giving more weight to higher scores. That weighted average reached {multiplier}×.', 'calibration.vsBase': 'vs. base sensitivity', 'calibration.overshoots': 'Overshoots', 'calibration.errorMap': 'Target-relative error map', 'calibration.errorMapLegend': 'Center = target · green inside · red outside', 'calibration.aimBias': 'Average aim bias', 'calibration.biasCentered': 'Centered', 'calibration.biasRight': 'Right', 'calibration.biasLeft': 'Left', 'calibration.biasUp': 'Above', 'calibration.biasDown': 'Below', 'calibration.howCalculated': 'How the score is calculated', 'calibration.errorControl': 'Average error control', 'calibration.overshootPenalty': 'Overshoot penalty', 'calibration.formulaExplanation': 'Accuracy measures time inside the target. Control converts average distance into a score. Smoothness evaluates abrupt changes in aim speed. Overshoots deduct points when the crosshair passes through the target and quickly moves away.', 'calibration.confidenceExplanation': 'Confidence considers the quality of the best score, how closely the competitive sensitivities converge, and completion of all five rounds.', 'calibration.candidateEvidence': 'Results from tested values', 'calibration.competitiveHint': 'Green rows contributed to the final average', 'calibration.previousSession': 'Previous calibration comparison', 'calibration.firstSession': 'This is the first recorded calibration for this game.',
  'calibration.adjust': 'ADJUST', 'calibration.measurementStage': 'Measurement', 'calibration.validationStage': 'Validation', 'calibration.validationReady': 'Measurements completed', 'calibration.validationHint': 'The two strongest values will now be compared on two new trajectories.', 'calibration.retryRound': 'This round was excluded from the calculation. Repeat it under the same conditions.',
  'calibration.issueInsufficientSamples': 'Round rejected because too few samples were collected', 'calibration.issueCanvasResized': 'Round rejected because the arena changed size', 'calibration.issueUnstableFrames': 'Round rejected because frame timing was too unstable', 'calibration.issueInterruptions': 'Round rejected because pointer lock was interrupted during measurement',
  'calibration.resultTitleRecommended': 'Confirmed sensitivity', 'calibration.resultTitleRange': 'Starting point and adjustment zone', 'calibration.resultTitleInconclusive': 'Provisional reference',
  'calibration.reasonConfirmed': 'Validation confirmed the strongest tested value with sufficient consistency.', 'calibration.reasonCloseCandidates': 'The strongest tested values were too close to justify one sensitivity.', 'calibration.reasonLowConsistency': 'The repeated measurements varied too much to support a reliable recommendation.', 'calibration.reasonLowSignal': 'This session did not produce enough signal to distinguish the sensitivities.', 'calibration.reasonIncomplete': 'The session did not collect every required valid round.', 'calibration.reasonValidationReversed': 'Both final trajectories favored the other tested value.',
  'calibration.rangeFromBase': 'range from {min}× to {max}× the base sensitivity', 'calibration.technicalConclusionV2': 'The report combined {rounds} valid rounds, {values} tested sensitivities, {repeatability}% repeatability, and {validation}% validation agreement. The displayed range spans {min}× to {max}×.',
  'calibration.repeatability': 'Repeatability', 'calibration.repeatabilityHint': 'Agreement between the two measurements of each sensitivity', 'calibration.validationAgreement': 'Final confirmation', 'calibration.validationAgreementHint': 'Agreement across both final trajectories',
  'calibration.formulaExplanationV2': 'Accuracy measures time inside the target. Control converts average error into a score. Smoothness uses a robust measure of speed changes. Overshoots deduct points.', 'calibration.confidenceExplanationV2': 'Confidence combines sample quality, repeatability, block agreement, separation between tested values, and final validation. It describes this session and does not guarantee in-game performance.',
  'calibration.testedValuesEvidence': 'Tested value comparison', 'calibration.competitiveHintV2': 'Each sensitivity has two measurements; the two strongest values receive two final comparisons', 'calibration.sampleQuality': 'Sample quality', 'calibration.blockAgreement': 'Block agreement', 'calibration.separation': 'Value separation', 'calibration.completedRounds': 'Valid rounds',
  'calibration.disclaimerV2': 'Experimental estimate based on this session and this tracking exercise. FOV, ADS, weapon behavior, fatigue, and game mechanics can change your preference. Confirm the range in the practice area and repeat the calibration on another day before making a large change.', 'calibration.insufficientCandidates': 'This game’s configurable precision produces fewer than three distinct sensitivities within ±35%. Use a higher base sensitivity or test directly in the game.', 'calibration.relativeMethod': 'Relative test · DPI does not change the comparison',
  'arena.currentRound': 'Current round', 'arena.calibrationComplete': 'Calibration complete', 'arena.roundComplete': 'Round complete', 'arena.ready': 'Ready to calibrate', 'arena.fiveRounds': 'All rounds have been recorded.', 'arena.allRounds': 'All valid rounds have been recorded.', 'arena.continueReady': 'Continue when you are ready.', 'arena.startHint': 'Start the test to prepare the first round.', 'arena.viewResult': 'View result', 'arena.nextRound': 'Next round', 'arena.startTest': 'Start test', 'arena.notScoring': 'This round is not scoring yet', 'arena.lockCursor': 'Click to lock the cursor', 'arena.testSensitivity': 'Test sensitivity',
  'warmup.kicker': 'FPS Warm-up', 'warmup.title': 'Get your aim ready before the match', 'warmup.subtitle': 'Choose a 1-minute exercise, adjust the difficulty, and warm up with your in-game sensitivity.', 'warmup.configure': 'Configure exercise', 'warmup.configureExercise': 'Configure {exercise}', 'warmup.sessionDuration': '{description} The session lasts {seconds} seconds.', 'warmup.difficulty': 'Difficulty', 'warmup.crosshair': 'Crosshair', 'warmup.start': 'Start warm-up', 'warmup.complete': 'Warm-up complete', 'warmup.level': 'Level', 'warmup.timeOnTarget': 'Time on target', 'warmup.hits': 'Hits', 'warmup.chooseTraining': 'Choose exercise', 'warmup.repeat': 'Repeat', 'warmup.prepareAim': 'Get your aim ready',
  'warmup.stepGame': 'Game', 'warmup.stepSettings': 'Settings', 'warmup.stepCrosshair': 'Crosshair', 'warmup.chooseGame': 'Choose your game', 'warmup.settingsTitle': 'Tune your sensitivity', 'warmup.crosshairTitle': 'Choose your crosshair', 'warmup.back': 'Back', 'warmup.next': 'Continue', 'warmup.exit': 'Exit', 'warmup.nextRound': 'Next round', 'warmup.nextLevelHint': 'Recommended next level: {level}', 'warmup.keepHardHint': 'Stay on Hard and try to beat your result.', 'warmup.adaptiveNextHint': 'The next round will adjust automatically based on your performance.', 'warmup.fixedNextHint': 'The next round will use a new path at {level}.',
  'warmup.reportTitle': 'Post-training report', 'warmup.reactionSpeed': 'Reaction speed', 'warmup.clickErrors': 'Click errors', 'warmup.bestStreak': 'Best streak', 'warmup.aimHeatmap': 'Aim heatmap', 'warmup.heatmapDescription': 'Green shows concentration; red shows errors and missed clicks.', 'warmup.noHeatmapData': 'Complete a round to generate the map.', 'warmup.overshootDirection': 'Predominant overshoot direction', 'warmup.overshootBalanced': 'Balanced center', 'warmup.overshootRight': 'Right', 'warmup.overshootLeft': 'Left', 'warmup.overshootUp': 'Up', 'warmup.overshootDown': 'Down', 'warmup.previousComparison': 'Previous session comparison', 'warmup.firstComparison': 'This is the first recorded session for this exercise.', 'warmup.nextRecommendation': 'Recommended next exercise', 'warmup.recommendationDescription': 'Suggestion based on the metric that limited this session the most.',
  'warmup.switch.name': 'Target switch', 'warmup.switch.description': 'Hold your crosshair on the target until it disappears and reappears in a new position.', 'warmup.switch.instruction': 'Keep your crosshair on the target to confirm each switch.', 'warmup.tracking.name': 'Continuous tracking', 'warmup.tracking.description': 'Follow a moving target for as long as possible without losing contact.', 'warmup.tracking.instruction': 'Track the target continuously. No clicking required.', 'warmup.flick.name': 'Target shooting', 'warmup.flick.description': 'Shoot the targets that appear across the arena before time runs out.', 'warmup.flick.instruction': 'Use the left mouse button to hit each target.',
  'warmup.reflex.name': 'Reflex', 'warmup.reflex.description': 'Hit the target before it disappears. Each level shortens the available reaction time.', 'warmup.reflex.instruction': 'Click the target before the reaction window runs out.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Three targets stay in the arena. Each hit replaces one at a new position.', 'warmup.gridshot.instruction': 'Switch quickly between the three targets while staying accurate.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Track a laterally moving target that changes direction during its path.', 'warmup.strafetrack.instruction': 'Keep your crosshair on the target through every direction change.',
  'difficulty.easy': 'Easy', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Hard', 'difficulty.adaptive': 'Adaptive', 'difficulty.easyDescription': 'Larger target and relaxed pace', 'difficulty.mediumDescription': 'Balanced pace and accuracy', 'difficulty.hardDescription': 'Smaller target and faster response', 'difficulty.adaptiveDescription': 'Balanced profile without automatic progression between rounds',
  'routine.kicker': 'FPS Routines', 'routine.title': 'Train five fundamentals in five minutes', 'routine.subtitle': 'Balanced presets designed to build precision, target switching, tracking, and fine control.', 'routine.configure': 'Configure routine', 'routine.phases': '5 phases · 1 minute each', 'routine.fundamentalsDescription': 'A balanced base of tracking, target switching, precision, and reaction.', 'routine.tacticalDescription': 'Fine control and micro-corrections for tactical games such as CS2 and Valorant.', 'routine.reactiveDescription': 'Smooth tracking, direction changes, and fast responses to new targets.', 'routine.phase': 'Phase {current} of {total}', 'routine.phaseComplete': 'Phase complete', 'routine.nextExercise': 'Next exercise: {exercise}', 'routine.complete': 'Routine complete', 'routine.totalScore': 'Total score', 'routine.start': 'Start routine', 'routine.nextPhase': 'Next phase', 'routine.repeatPhase': 'Repeat phase', 'routine.setupTitle': 'Configure {routine}', 'routine.setupDescription': 'Set your game, sensitivity, difficulty, and crosshair once for all five phases.', 'routine.selectPreset': 'Choose a routine',
  'converter.kicker': '360° Conversion', 'converter.title': 'Sensitivity converter', 'converter.subtitle': 'Transfer your hipfire sensitivity while preserving the same physical distance for a full 360° turn.', 'converter.from': 'Convert from', 'converter.to': 'Convert to', 'converter.currentSensitivity': 'Current sensitivity', 'converter.sourceDpi': 'Source DPI', 'converter.convertedSensitivity': 'Converted sensitivity', 'converter.targetDpi': 'Target DPI', 'converter.swap': 'Swap games', 'converter.copy': 'Copy converted sensitivity', 'converter.nonlinear': 'This pair includes a non-linear scale. PUBG and Battlefield 6 require a specific FOV and settings profile for a reliable conversion.', 'converter.invalidSensitivity': 'Enter a valid sensitivity greater than zero.', 'converter.invalidDpi': 'Enter valid DPI values greater than zero.', 'converter.estimated': 'ARC Raiders uses an approximate equivalence. Confirm it with a 360° turn in-game.', 'converter.sourceRange': 'The entered sensitivity is outside the configurable range for {game}.', 'converter.targetRange': 'The result is outside the configurable range for {game}.', 'converter.linear': 'Linear hipfire conversion with DPI adjustment. FOV and ADS may change the perceived feel.',
  'polling.diagnostics': 'Diagnostics', 'polling.title': 'Polling rate test', 'polling.subtitle': 'Measure how often the browser receives updates from your mouse.', 'polling.moveTip': 'Move the mouse quickly in circles during the 8-second test.', 'polling.performanceTip': 'Close demanding programs to reduce interference in the result.', 'polling.rawSupported': 'Raw input is supported in this browser.', 'polling.compatibleMode': 'Using compatibility mode. For better accuracy, use Chrome or Edge.', 'polling.measuring': 'MEASURING NOW', 'polling.complete': 'TEST COMPLETE', 'polling.ready': 'READY TO MEASURE', 'polling.probableHz': 'Likely Hz', 'polling.observedHz': 'Observed Hz', 'polling.samples': '{samples} valid samples', 'polling.duration': '{seconds}-second test', 'polling.remaining': '{seconds}s remaining', 'polling.testAgain': 'Test again', 'polling.start': 'Start test', 'polling.observedPeak': 'Observed peak', 'polling.validSamples': 'Valid samples', 'polling.probableRate': 'Likely polling rate', 'polling.disclaimer': 'Estimated from events delivered to the browser. The operating system, CPU load, and event coalescing can affect the reading, especially at 4K and 8K.',
  'buttons.diagnostics': 'Input diagnostics', 'buttons.title': 'Mouse and keyboard test', 'buttons.subtitle': 'Select a device and press one or more inputs at the same time to verify activation.', 'buttons.device': 'Device to test', 'buttons.keyboard': 'Keyboard', 'buttons.mouseArea': 'Mouse button test area', 'buttons.keyboardArea': 'Keyboard test area', 'buttons.pressedNow': 'Pressed now', 'buttons.waiting': 'Waiting for input', 'buttons.mousePrompt': 'Click or scroll the mouse', 'buttons.keyboardPrompt': 'Press any key', 'buttons.scrollUp': 'Scroll up', 'buttons.scrollDown': 'Scroll down', 'buttons.scrolls': 'Scrolls', 'buttons.coverage': 'COVERAGE', 'buttons.keysTested': 'Keys tested', 'buttons.actions': 'ACTIVATIONS', 'buttons.totalRecorded': 'Total recorded', 'buttons.simultaneous': 'SIMULTANEOUS', 'buttons.pressedCount': 'Pressed now', 'buttons.reset': 'Reset counters', 'mouse.left': 'Left', 'mouse.middle': 'Wheel', 'mouse.right': 'Right', 'mouse.back': 'Back', 'mouse.forward': 'Forward', 'key.space': 'Space',

  'calibration.reasonSplitCandidates': 'The strongest tested values appeared at separated points and did not form a continuous range.',
  'calibration.confirmedValue': 'Confirmed value', 'calibration.startingPoint': 'Recommended starting point', 'calibration.bestObserved': 'Best observed value', 'calibration.recommendationStrength': 'Recommendation strength',
  'calibration.directionLower': '{percent}% lower than the {base} baseline', 'calibration.directionHigher': '{percent}% higher than the {base} baseline', 'calibration.directionNearBase': 'Result close to the {base} baseline sensitivity',
  'calibration.whatToDoNow': 'What to do now', 'calibration.directionIndicated': 'Indicated direction', 'calibration.adjustmentZone': 'Adjustment zone', 'calibration.refinementRequired': 'Refinement required', 'calibration.zoneHint': 'Continuous region with equivalent performance', 'calibration.singlePointHint': 'One value carried the strongest evidence in this session', 'calibration.noContinuousZoneHint': 'The session did not find a reliable continuous zone', 'calibration.nextTest': 'Next test', 'calibration.nextTestHint': 'Compare these three values in a short refinement stage', 'calibration.finalValidation': 'Final validation',
  'calibration.validationUnavailable': 'This session does not have final validation yet.',
  'calibration.conclusionConfirmed': 'Sensitivity {best} achieved the highest score, {bestScore}, and led the second value by {gap} points. Both final trajectories preserved that result. It was the best-supported point in this session.',
  'calibration.conclusionRange': 'The strongest results formed a continuous region from {zoneMin} to {zoneMax}. Value {best} achieved the highest score, {bestScore}, while {second} stayed close at {secondScore}. Start with the highlighted value and use the zone only for small adjustments.',
  'calibration.conclusionSplit': 'The best isolated result was {best}, scoring {bestScore}, but {second} also stayed close at {secondScore}. A weaker intermediate value separates them, so the data does not form a continuous range. Use {best} as a provisional reference and run only the final refinement.',
  'calibration.conclusionValidationReversed': 'Initial measurements favored {best}, but {validationWinner} won both final trajectories. The initial reference was reversed and should not be applied as a recommendation. Repeat the full calibration on another day.',
  'calibration.conclusionLowConsistency': 'Repeated measurements varied beyond the acceptable level. Combined consistency was {repeatability}% and block agreement was {blockAgreement}%. Value {best} was the best observed result, but it should not replace the current setting without refinement.',
  'calibration.conclusionIncomplete': 'The session did not collect every required valid round. Value {best} is only a reference from the available data and does not represent a completed recommendation.',
  'calibration.conclusionLowSignal': 'Scores were too close or too low to identify a stable region. The best observed value was {best}, scoring {bestScore}, only {gap} point above the runner-up.',
  'calibration.scoreGapHint': '{gap}-point lead over the runner-up', 'calibration.playerConsistency': 'Player consistency', 'calibration.playerConsistencyHint': 'How well performance repeated across blocks and sensitivities',
  'calibration.strengthExplanation': 'Recommendation strength considers value separation, consistency, block agreement, and validation. Excellent data collection can still produce a weak recommendation when results conflict.', 'calibration.testedValuesHint': 'The highlight marks the best observed result. Only neighboring tested values can form an adjustment zone.',
  'calibration.collectionQuality': 'Collection quality', 'calibration.collectionQualityHint': 'Samples, stability, and completed rounds', 'calibration.recommendationStrengthHint': 'How clearly the evidence supports the indicated direction', 'calibration.completedRoundsHint': 'Rounds accepted by quality control',
  'calibration.disclaimerV3': 'Experimental estimate from this tracking session. The highlighted point was actually tested. An adjustment zone is shown only when adjacent sensitivities produced equivalent performance. FOV, ADS, weapon, fatigue, and game mechanics can change preference. Confirm the value in the practice range before making a permanent change.',
  'calibration.reasonValidationSplit': 'The final comparison was split and did not confirm one exact point.',
  'calibration.conclusionValidationSplit': 'The final comparison was divided between both tested values. The {validationRecord} result did not confirm one exact point. Use {best} only as a provisional reference or repeat the full calibration on another day.',
  'calibration.validationStatusConfirmed': 'Confirmed',
  'calibration.validationStatusSplit': 'Split comparison',
  'calibration.validationStatusReversed': 'Result reversed',
  'calibration.validationStatusUnavailable': 'Not run',
  'calibration.validationConfirmedCount': '{confirmed} of {total} final blocks favored {value}.',
  'calibration.validationSplitCount': 'The comparison ended {confirmed}–{alternative}, with {ties} tie(s). {value} led the final average by {gap} point(s).',
  'calibration.validationReversedCount': '{value} won {alternative} of {total} final trajectories and reversed the initial result.',
  'calibration.refinementStatus': 'Refinement stage',
  'calibration.refinementCompleted': 'Final refinement complete',
  'calibration.refinementCompletedHint': 'The process ends here to avoid repeated narrowing and false precision.',
  'calibration.refinementNotNeeded': 'Refinement not required',
  'calibration.refinementNotNeededHint': 'The evidence already supports a practical conclusion or calls for a new full session.',
  'calibration.validationColumn': 'Validation',
  'calibration.refineFinal': 'Run final refinement',
  'calibration.finish': 'Use this result',
  'calibration.validationTieShort': 'tie',
  'calibration.validationSplitTieCount': 'The comparison ended {confirmed}–{alternative}, with {ties} tie(s). The final average remained inside the technical tie margin.',
  'calibration.closeReport': 'Close report',
  'calibration.roundCountCompact': '{measurements} measurements · {validation} final rounds',
  'calibration.horizontalFov': 'Horizontal FOV', 'calibration.cmPer360': 'Distance for 360°', 'calibration.cmPer360Unavailable': 'Physical profile unavailable',
  'calibration.historyTitle': 'Calibration history', 'calibration.historyCount': '{count} saved sessions', 'calibration.historyEmpty': 'Complete a valid calibration to start this game’s history.', 'calibration.historyPhysicalAverage': 'Physical session average: {value} cm/360°. History shows stability but does not change the current session calculation.',
  'converter.cmPer360': 'Distance for 360°',
  'calibration.vsBaseClear': 'vs. base sensitivity', 'calibration.formulaExplanationPhysical': 'Accuracy measures time inside the target. Control turns average error into a score. Smoothness uses a robust measure of speed changes. Target overshoots deduct points.',
  'calibration.setupDescriptionPhysical': 'Choose the game, enter your sensitivity, DPI, and horizontal FOV. The session uses up to {rounds} rounds of {seconds} seconds, including two final comparisons between the strongest values.',
  'calibration.physicalProfile': 'Physical profile · {dpi} DPI · horizontal FOV {fov}°', 'calibration.relativeProfileNotice': 'This game does not yet have a confirmed linear scale in $ENSI. Calibration remains relative and does not display cm/360°.',
  'nav.gamepad': 'Controller', 'gamepad.diagnostics': 'Controller diagnostics', 'gamepad.title': 'Gamepad test', 'gamepad.subtitle': 'Real-time readings for buttons, sticks, triggers, and controller stability.', 'gamepad.waitingTitle': 'Connect and activate a controller', 'gamepad.waitingDescription': 'Press any button on the controller so the browser can detect the device.', 'gamepad.connectedControllers': 'Connected controllers', 'gamepad.controller': 'Controller', 'gamepad.unknown': 'Unknown controller', 'gamepad.index': 'Index', 'gamepad.timestamp': 'Timestamp', 'gamepad.status': 'Status', 'gamepad.connected': 'Connected', 'gamepad.rumble': 'Test vibration', 'gamepad.pressed': 'Pressed buttons', 'gamepad.leftStick': 'Left stick', 'gamepad.rightStick': 'Right stick', 'gamepad.circularity': 'Circularity error', 'gamepad.rawAxes': 'Raw axis values', 'gamepad.resetPath': 'Clear paths',

}

const es: Record<TranslationKey, string> = {
  ...pt,
  'meta.title': '$ENSI - Calentamiento, sensibilidad y diagnostico FPS',
  'calibration.targetSpeed': 'Velocidad del objetivo',
  'buttons.mouse': 'Ratón',
  'common.stability': 'Estabilidad', 'common.samples': 'Muestras',
  'language.selector': 'Idioma de la página',
  'nav.routine': 'Rutina', 'nav.warmup': 'Calentamiento', 'nav.calibration': 'Calibración de sensibilidad', 'nav.converter': 'Conversor', 'nav.polling': 'Tasa de sondeo', 'nav.buttons': 'Prueba de botones',
  'header.rounds': '{completed}/{total} rondas', 'header.openSettings': 'Abrir configuración', 'header.dailyRoutine': 'Rutina diaria', 'header.aimTraining': 'Entrenamiento de puntería', 'header.conversion': 'Conversión 360°', 'header.inputDiagnostics': 'Diagnóstico de entrada', 'header.mouseDiagnostics': 'Diagnóstico del ratón',
  'common.accuracy': 'Precisión', 'common.meanError': 'Error medio', 'common.smoothness': 'Suavidad', 'common.sensitivity': 'Sensibilidad', 'common.time': 'Tiempo', 'common.score': 'Puntuación', 'common.result': 'Resultado', 'common.restart': 'Reiniciar', 'common.close': 'Cerrar', 'common.mouseDpi': 'DPI del ratón', 'common.gameReference': 'Juego de referencia',
  'calibration.live': 'En vivo', 'calibration.roundOf': 'Ronda {round} de {total}', 'calibration.testSensitivity': 'Sensibilidad en prueba', 'calibration.speed': 'Velocidad {speed}', 'calibration.prepareHand': 'Prepara la mano. La ronda todavía no puntúa.', 'calibration.warmup': 'El objetivo ya está en movimiento. Usa este segundo para ajustar el seguimiento.', 'calibration.guidance': 'Muévete con naturalidad. Cada sensibilidad probada recibe la misma trayectoria controlada dentro del bloque.', 'calibration.trackingActive': 'Seguimiento activo · haz clic en la arena si se libera el cursor', 'calibration.base': 'Base: {game}', 'calibration.pause': 'Pausar', 'calibration.resume': 'Reanudar',
  'calibration.setupTitle': 'Configurar antes de la prueba', 'calibration.setupDescription': 'Elige un juego, introduce tu sensibilidad actual y selecciona la velocidad del objetivo. La sesión usa hasta {rounds} rondas de {seconds} segundos, incluidas dos comparaciones finales entre los dos valores más fuertes.', 'calibration.currentSensitivity': 'Sensibilidad actual en {game}', 'calibration.normal': 'Normal', 'calibration.fast': 'Rápido', 'calibration.fastBadge': 'Rápida', 'calibration.normalDescription': 'Velocidad equilibrada para una calibración estándar', 'calibration.fastDescription': 'Objetivo más rápido para un seguimiento más exigente', 'calibration.crosshairType': 'Tipo de mira', 'calibration.baseSensitivity': 'Sensibilidad base en {game}', 'calibration.saveStart': 'Guardar e iniciar prueba', 'calibration.save': 'Guardar configuración',
  'calibration.landingTitle': 'Encuentra un rango consistente de sensibilidad', 'calibration.landingDescription': 'Mediciones repetidas con trayectorias equivalentes comparan pequeñas variaciones e indican cuándo los datos sostienen un valor, un rango o ningún resultado concluyente.', 'calibration.landingStart': 'Iniciar calibración', 'calibration.landingPreview': 'Demostración de tracking', 'calibration.landingRoundsLabel': 'rondas máximas', 'calibration.landingSecondsLabel': 'segundos cada una', 'calibration.landingStepConfigure': 'Configura', 'calibration.landingStepConfigureDescription': 'Elige el juego, tu sensibilidad actual y la velocidad del objetivo.', 'calibration.landingStepTrack': 'Haz el tracking', 'calibration.landingStepTrackDescription': 'Sigue el objetivo mientras probamos pequeñas variaciones.', 'calibration.landingStepResult': 'Recibe el resultado', 'calibration.landingStepResultDescription': 'Recibe un valor confirmado, un rango sugerido o un resultado no concluyente.',
  'crosshair.classic': 'Clásica', 'crosshair.dot': 'Punto', 'crosshair.circle': 'Circular', 'crosshair.plus': 'Cruz completa', 'crosshair.classicDescription': 'Líneas finas con el centro abierto', 'crosshair.dotDescription': 'Punto central limpio', 'crosshair.circleDescription': 'Anillo con punto central', 'crosshair.plusDescription': 'Mira compacta y directa',
  'calibration.resultTitle': 'Sensibilidad recomendada', 'calibration.resultDescription': 'Tu mejor equilibrio entre precisión, control y suavidad apareció en {multiplier}× de la configuración inicial con velocidad {speed}.', 'calibration.disclaimer': 'Estimación basada en esta sesión. Valida la recomendación en el campo de práctica del juego antes de competir.', 'calibration.redo': 'Reiniciar calibración', 'calibration.refine': 'Hacer refinamiento final',
  'calibration.fromBaseSensitivity': 'desde la sensibilidad base {sensitivity}', 'calibration.confidence': 'Confianza de la sesión', 'calibration.confidenceHigh': 'Alta', 'calibration.confidenceMedium': 'Moderada', 'calibration.confidenceExploratory': 'Exploratoria', 'calibration.whyTitle': 'Cómo interpretar este resultado', 'calibration.technicalConclusion': 'El mejor resultado individual apareció en {best}×. Para reducir el efecto de la suerte en una sola ronda, el cálculo combinó los {count} valores probados más competitivos entre {min}× y {max}×, dando más peso a las puntuaciones más altas. Ese promedio ponderado llegó a {multiplier}×.', 'calibration.vsBase': 'vs. sensibilidad base', 'calibration.overshoots': 'Overshoots', 'calibration.errorMap': 'Mapa de error relativo al objetivo', 'calibration.errorMapLegend': 'Centro = objetivo · verde dentro · rojo fuera', 'calibration.aimBias': 'Tendencia media de la mira', 'calibration.biasCentered': 'Centrada', 'calibration.biasRight': 'A la derecha', 'calibration.biasLeft': 'A la izquierda', 'calibration.biasUp': 'Arriba', 'calibration.biasDown': 'Abajo', 'calibration.howCalculated': 'Cómo se calcula la puntuación', 'calibration.errorControl': 'Control del error medio', 'calibration.overshootPenalty': 'Penalización por overshoots', 'calibration.formulaExplanation': 'La precisión mide el tiempo dentro del objetivo. El control convierte la distancia media en una puntuación. La suavidad evalúa cambios bruscos en la velocidad de la mira. Los overshoots restan puntos cuando la mira atraviesa el objetivo y se aleja rápidamente.', 'calibration.confidenceExplanation': 'La confianza considera la calidad de la mejor puntuación, la proximidad entre las sensibilidades competitivas y la finalización de las cinco rondas.', 'calibration.candidateEvidence': 'Resultados de los valores probados', 'calibration.competitiveHint': 'Las filas verdes participaron en el promedio final', 'calibration.previousSession': 'Comparación con la calibración anterior', 'calibration.firstSession': 'Esta es la primera calibración registrada para este juego.',
  'calibration.adjust': 'AJUSTE', 'calibration.measurementStage': 'Medición', 'calibration.validationStage': 'Validación', 'calibration.validationReady': 'Mediciones completadas', 'calibration.validationHint': 'Ahora los dos valores más fuertes se compararán en dos trayectorias nuevas.', 'calibration.retryRound': 'La ronda no entró en el cálculo. Repítela en las mismas condiciones.',
  'calibration.issueInsufficientSamples': 'Ronda rechazada por falta de muestras', 'calibration.issueCanvasResized': 'Ronda rechazada porque la arena cambió de tamaño', 'calibration.issueUnstableFrames': 'Ronda rechazada por demasiada inestabilidad de frames', 'calibration.issueInterruptions': 'Ronda rechazada porque el bloqueo del cursor se interrumpió durante la medición',
  'calibration.resultTitleRecommended': 'Sensibilidad confirmada', 'calibration.resultTitleRange': 'Punto inicial y zona de ajuste', 'calibration.resultTitleInconclusive': 'Referencia provisional',
  'calibration.reasonConfirmed': 'La validación confirmó el valor probado más fuerte con suficiente consistencia.', 'calibration.reasonCloseCandidates': 'Los valores probados más fuertes quedaron demasiado cerca para justificar una sola sensibilidad.', 'calibration.reasonLowConsistency': 'Las mediciones repetidas variaron demasiado para sostener una recomendación fiable.', 'calibration.reasonLowSignal': 'La sesión no produjo señal suficiente para diferenciar las sensibilidades.', 'calibration.reasonIncomplete': 'La sesión no reunió todas las rondas válidas necesarias.', 'calibration.reasonValidationReversed': 'Las dos trayectorias finales favorecieron el otro valor probado.',
  'calibration.rangeFromBase': 'rango entre {min}× y {max}× de la sensibilidad base', 'calibration.technicalConclusionV2': 'El informe combinó {rounds} rondas válidas, {values} sensibilidades probadas, una repetibilidad del {repeatability}% y una concordancia de validación del {validation}%. El rango mostrado quedó entre {min}× y {max}×.',
  'calibration.repeatability': 'Repetibilidad', 'calibration.repeatabilityHint': 'Proximidad entre las dos mediciones de cada sensibilidad', 'calibration.validationAgreement': 'Confirmación final', 'calibration.validationAgreementHint': 'Concordancia en las dos trayectorias finales',
  'calibration.formulaExplanationV2': 'La precisión mide el tiempo dentro del objetivo. El control convierte el error medio en puntuación. La suavidad usa una medida robusta de los cambios de velocidad. Los overshoots descuentan puntos.', 'calibration.confidenceExplanationV2': 'La confianza combina calidad de muestras, repetibilidad, concordancia entre bloques, separación de los valores probados y validación final. Describe esta sesión y no garantiza rendimiento dentro del juego.',
  'calibration.testedValuesEvidence': 'Comparación de valores probados', 'calibration.competitiveHintV2': 'Cada sensibilidad tiene dos mediciones; los dos valores más fuertes reciben dos comparaciones finales', 'calibration.sampleQuality': 'Calidad de muestras', 'calibration.blockAgreement': 'Concordancia entre bloques', 'calibration.separation': 'Separación de valores', 'calibration.completedRounds': 'Rondas válidas',
  'calibration.disclaimerV2': 'Estimación experimental basada en esta sesión y en este ejercicio de tracking. El FOV, ADS, arma, fatiga y mecánicas del juego pueden cambiar la preferencia. Confirma el rango en el campo de práctica y repite la calibración otro día antes de aplicar un cambio grande.', 'calibration.insufficientCandidates': 'La precisión configurable de este juego genera menos de tres sensibilidades distintas dentro de ±35%. Usa una sensibilidad base mayor o prueba directamente en el juego.', 'calibration.relativeMethod': 'Prueba relativa · los DPI no cambian la comparación',
  'arena.currentRound': 'Ronda actual', 'arena.calibrationComplete': 'Calibración completada', 'arena.roundComplete': 'Ronda completada', 'arena.ready': 'Todo listo para calibrar', 'arena.fiveRounds': 'Se registraron todas las rondas.', 'arena.allRounds': 'Se registraron todas las rondas válidas.', 'arena.continueReady': 'Continúa cuando estés preparado.', 'arena.startHint': 'Inicia la prueba para preparar la primera ronda.', 'arena.viewResult': 'Ver resultado', 'arena.nextRound': 'Siguiente ronda', 'arena.startTest': 'Iniciar prueba', 'arena.notScoring': 'Esta ronda todavía no puntúa', 'arena.lockCursor': 'Haz clic para bloquear el cursor', 'arena.testSensitivity': 'Sensi en prueba',
  'warmup.kicker': 'Calentamiento FPS', 'warmup.title': 'Prepara tu puntería antes de la partida', 'warmup.subtitle': 'Elige un ejercicio de 1 minuto, ajusta la dificultad y calienta con la sensibilidad de tu juego.', 'warmup.configure': 'Configurar ejercicio', 'warmup.configureExercise': 'Configurar {exercise}', 'warmup.sessionDuration': '{description} La sesión dura {seconds} segundos.', 'warmup.difficulty': 'Dificultad', 'warmup.crosshair': 'Mira', 'warmup.start': 'Iniciar calentamiento', 'warmup.complete': 'Calentamiento completado', 'warmup.level': 'Nivel', 'warmup.timeOnTarget': 'Tiempo en el objetivo', 'warmup.hits': 'Aciertos', 'warmup.chooseTraining': 'Elegir ejercicio', 'warmup.repeat': 'Repetir', 'warmup.prepareAim': 'Prepara la mira',
  'warmup.stepGame': 'Juego', 'warmup.stepSettings': 'Ajustes', 'warmup.stepCrosshair': 'Mira', 'warmup.chooseGame': 'Elige tu juego', 'warmup.settingsTitle': 'Ajusta tu sensibilidad', 'warmup.crosshairTitle': 'Elige tu mira', 'warmup.back': 'Volver', 'warmup.next': 'Continuar', 'warmup.exit': 'Salir', 'warmup.nextRound': 'Siguiente ronda', 'warmup.nextLevelHint': 'Siguiente nivel recomendado: {level}', 'warmup.keepHardHint': 'Continúa en Difícil e intenta superar tu resultado.', 'warmup.adaptiveNextHint': 'La siguiente ronda se ajustará automáticamente según tu rendimiento.', 'warmup.fixedNextHint': 'La siguiente ronda tendrá una nueva trayectoria en {level}.',
  'warmup.reportTitle': 'Informe posterior al entrenamiento', 'warmup.reactionSpeed': 'Velocidad de reacción', 'warmup.clickErrors': 'Errores de clic', 'warmup.bestStreak': 'Mejor racha', 'warmup.aimHeatmap': 'Mapa de calor de la mira', 'warmup.heatmapDescription': 'El verde muestra concentración; el rojo, errores y clics fallidos.', 'warmup.noHeatmapData': 'Completa una ronda para generar el mapa.', 'warmup.overshootDirection': 'Dirección predominante de los overshoots', 'warmup.overshootBalanced': 'Centro equilibrado', 'warmup.overshootRight': 'Derecha', 'warmup.overshootLeft': 'Izquierda', 'warmup.overshootUp': 'Arriba', 'warmup.overshootDown': 'Abajo', 'warmup.previousComparison': 'Comparación con la sesión anterior', 'warmup.firstComparison': 'Esta es la primera sesión registrada en este ejercicio.', 'warmup.nextRecommendation': 'Siguiente ejercicio recomendado', 'warmup.recommendationDescription': 'Sugerencia basada en la métrica que más limitó esta sesión.',
  'warmup.switch.name': 'Cambio de objetivo', 'warmup.switch.description': 'Mantén la mira sobre el objetivo hasta que desaparezca y reaparezca en una nueva posición.', 'warmup.switch.instruction': 'Mantén la mira sobre el objetivo para confirmar cada cambio.', 'warmup.tracking.name': 'Seguimiento continuo', 'warmup.tracking.description': 'Sigue un objetivo en movimiento el mayor tiempo posible sin perder el contacto.', 'warmup.tracking.instruction': 'Sigue el objetivo continuamente. No es necesario hacer clic.', 'warmup.flick.name': 'Tiro a objetivos', 'warmup.flick.description': 'Dispara a los objetivos que aparecen por la arena antes de que se acabe el tiempo.', 'warmup.flick.instruction': 'Usa el botón izquierdo para acertar cada objetivo.',
  'warmup.reflex.name': 'Reflejos', 'warmup.reflex.description': 'Acierta el objetivo antes de que desaparezca. Cada nivel reduce el tiempo disponible para reaccionar.', 'warmup.reflex.instruction': 'Haz clic en el objetivo antes de que se agote el tiempo de reacción.', 'warmup.gridshot.name': 'Gridshot', 'warmup.gridshot.description': 'Tres objetivos permanecen en la arena. Cada acierto sustituye uno en una nueva posición.', 'warmup.gridshot.instruction': 'Alterna rápidamente entre los tres objetivos sin perder precisión.', 'warmup.strafetrack.name': 'Strafetrack', 'warmup.strafetrack.description': 'Sigue un objetivo que se mueve lateralmente y cambia de dirección durante el recorrido.', 'warmup.strafetrack.instruction': 'Mantén la mira en el objetivo durante los cambios de dirección.',
  'difficulty.easy': 'Fácil', 'difficulty.medium': 'Normal', 'difficulty.hard': 'Difícil', 'difficulty.adaptive': 'Adaptativa', 'difficulty.easyDescription': 'Objetivo mayor y ritmo suave', 'difficulty.mediumDescription': 'Equilibrio entre ritmo y precisión', 'difficulty.hardDescription': 'Objetivo menor y respuesta rápida', 'difficulty.adaptiveDescription': 'Perfil equilibrado sin progresión automática entre rondas',
  'routine.kicker': 'Rutinas FPS', 'routine.title': 'Entrena cinco fundamentos en cinco minutos', 'routine.subtitle': 'Presets equilibrados para desarrollar precisión, cambio de objetivos, tracking y control fino.', 'routine.configure': 'Configurar rutina', 'routine.phases': '5 fases · 1 minuto cada una', 'routine.fundamentalsDescription': 'Una base equilibrada de tracking, cambio de objetivos, precisión y reacción.', 'routine.tacticalDescription': 'Control fino y microcorrecciones para juegos tácticos como CS2 y Valorant.', 'routine.reactiveDescription': 'Tracking fluido, cambios de dirección y respuesta rápida a nuevos objetivos.', 'routine.phase': 'Fase {current} de {total}', 'routine.phaseComplete': 'Fase completada', 'routine.nextExercise': 'Siguiente ejercicio: {exercise}', 'routine.complete': 'Rutina completada', 'routine.totalScore': 'Puntuación total', 'routine.start': 'Iniciar rutina', 'routine.nextPhase': 'Siguiente fase', 'routine.repeatPhase': 'Repetir fase', 'routine.setupTitle': 'Configurar {routine}', 'routine.setupDescription': 'Define juego, sensibilidad, dificultad y mira una sola vez para las cinco fases.', 'routine.selectPreset': 'Elige una rutina',
  'converter.kicker': 'Conversión 360°', 'converter.title': 'Conversor de sensibilidad', 'converter.subtitle': 'Transfiere tu sensibilidad de disparo desde la cadera manteniendo la misma distancia física para completar un giro de 360°.', 'converter.from': 'Convertir de', 'converter.to': 'Convertir a', 'converter.currentSensitivity': 'Sensibilidad actual', 'converter.sourceDpi': 'DPI de origen', 'converter.convertedSensitivity': 'Sensibilidad convertida', 'converter.targetDpi': 'DPI de destino', 'converter.swap': 'Intercambiar juegos', 'converter.copy': 'Copiar sensibilidad convertida', 'converter.nonlinear': 'Este par incluye una escala no lineal. PUBG y Battlefield 6 requieren un perfil específico de FOV y configuración para una conversión fiable.', 'converter.invalidSensitivity': 'Introduce una sensibilidad válida mayor que cero.', 'converter.invalidDpi': 'Introduce valores de DPI válidos mayores que cero.', 'converter.estimated': 'ARC Raiders utiliza una equivalencia aproximada. Confírmala con un giro de 360° dentro del juego.', 'converter.sourceRange': 'La sensibilidad introducida está fuera del intervalo configurable de {game}.', 'converter.targetRange': 'El resultado está fuera del intervalo configurable de {game}.', 'converter.linear': 'Conversión lineal de disparo desde la cadera con ajuste de DPI. El FOV y el ADS pueden cambiar la sensación visual.',
  'polling.diagnostics': 'Diagnóstico', 'polling.title': 'Prueba de tasa de sondeo', 'polling.subtitle': 'Mide la frecuencia con la que el navegador recibe actualizaciones del ratón.', 'polling.moveTip': 'Haz movimientos rápidos y circulares durante los 8 segundos.', 'polling.performanceTip': 'Cierra los programas pesados para reducir interferencias en el resultado.', 'polling.rawSupported': 'La entrada sin procesar es compatible con este navegador.', 'polling.compatibleMode': 'Usando el modo compatible. Para obtener mayor precisión, usa Chrome o Edge.', 'polling.measuring': 'MIDIENDO AHORA', 'polling.complete': 'PRUEBA COMPLETADA', 'polling.ready': 'LISTO PARA MEDIR', 'polling.probableHz': 'Hz probables', 'polling.observedHz': 'Hz observados', 'polling.samples': '{samples} muestras válidas', 'polling.duration': '{seconds} segundos de prueba', 'polling.remaining': 'Quedan {seconds}s', 'polling.testAgain': 'Probar de nuevo', 'polling.start': 'Iniciar prueba', 'polling.observedPeak': 'Pico observado', 'polling.validSamples': 'Muestras válidas', 'polling.probableRate': 'Tasa de sondeo probable', 'polling.disclaimer': 'Resultado estimado a partir de los eventos entregados al navegador. El sistema operativo, la carga de la CPU y la agrupación de eventos pueden alterar la medición, especialmente en 4K y 8K.',
  'buttons.diagnostics': 'Diagnóstico de entrada', 'buttons.title': 'Prueba de ratón y teclado', 'buttons.subtitle': 'Selecciona el dispositivo y pulsa una o varias entradas al mismo tiempo para comprobar su activación.', 'buttons.device': 'Dispositivo para probar', 'buttons.keyboard': 'Teclado', 'buttons.mouseArea': 'Área de prueba de los botones del ratón', 'buttons.keyboardArea': 'Área de prueba del teclado', 'buttons.pressedNow': 'Pulsado ahora', 'buttons.waiting': 'Esperando entrada', 'buttons.mousePrompt': 'Haz clic o desplaza la rueda', 'buttons.keyboardPrompt': 'Pulsa cualquier tecla', 'buttons.scrollUp': 'Rueda hacia arriba', 'buttons.scrollDown': 'Rueda hacia abajo', 'buttons.scrolls': 'Desplazamientos', 'buttons.coverage': 'COBERTURA', 'buttons.keysTested': 'Teclas probadas', 'buttons.actions': 'ACTIVACIONES', 'buttons.totalRecorded': 'Total registrado', 'buttons.simultaneous': 'SIMULTÁNEAS', 'buttons.pressedCount': 'Pulsadas ahora', 'buttons.reset': 'Reiniciar contadores', 'mouse.left': 'Izquierdo', 'mouse.middle': 'Rueda', 'mouse.right': 'Derecho', 'mouse.back': 'Atrás', 'mouse.forward': 'Adelante', 'key.space': 'Espacio',

  'calibration.reasonSplitCandidates': 'Los mejores valores probados aparecieron en puntos separados y no formaron un rango continuo.',
  'calibration.confirmedValue': 'Valor confirmado', 'calibration.startingPoint': 'Punto inicial recomendado', 'calibration.bestObserved': 'Mejor valor observado', 'calibration.recommendationStrength': 'Fuerza de la recomendación',
  'calibration.directionLower': 'Reducción del {percent}% respecto a la base {base}', 'calibration.directionHigher': 'Aumento del {percent}% respecto a la base {base}', 'calibration.directionNearBase': 'Resultado cercano a la sensibilidad base {base}',
  'calibration.whatToDoNow': 'Qué hacer ahora', 'calibration.directionIndicated': 'Dirección indicada', 'calibration.adjustmentZone': 'Zona de ajuste', 'calibration.refinementRequired': 'Se requiere refinamiento', 'calibration.zoneHint': 'Región continua con rendimiento equivalente', 'calibration.singlePointHint': 'Un único valor reunió la evidencia más fuerte de la sesión', 'calibration.noContinuousZoneHint': 'La sesión no encontró una zona continua fiable', 'calibration.nextTest': 'Próxima prueba', 'calibration.nextTestHint': 'Compara estos tres valores en una etapa corta de refinamiento', 'calibration.finalValidation': 'Validación final',
  'calibration.validationUnavailable': 'Esta sesión todavía no tiene validación final.',
  'calibration.conclusionConfirmed': 'La sensibilidad {best} obtuvo la puntuación más alta, {bestScore}, y superó al segundo valor por {gap} puntos. Las dos trayectorias finales mantuvieron ese resultado. Fue el punto con mayor respaldo de la sesión.',
  'calibration.conclusionRange': 'Los mejores resultados formaron una región continua entre {zoneMin} y {zoneMax}. El valor {best} obtuvo la puntuación más alta, {bestScore}, mientras {second} quedó cerca con {secondScore}. Empieza con el valor destacado y usa la zona solamente para ajustes pequeños.',
  'calibration.conclusionSplit': 'El mejor resultado aislado fue {best}, con {bestScore}, pero {second} también quedó cerca con {secondScore}. Un valor intermedio más débil los separa, por lo que los datos no forman un rango continuo. Usa {best} como referencia provisional y realiza solo el refinamiento final.',
  'calibration.conclusionValidationReversed': 'Las mediciones iniciales favorecieron {best}, pero {validationWinner} ganó las dos trayectorias finales. La referencia inicial fue revertida y no debe aplicarse como recomendación. Repite la calibración completa otro día.',
  'calibration.conclusionLowConsistency': 'Las repeticiones variaron más de lo aceptable. La consistencia combinada fue del {repeatability}% y la concordancia entre bloques del {blockAgreement}%. El valor {best} fue el mejor observado, pero no debería sustituir tu configuración actual sin refinamiento.',
  'calibration.conclusionIncomplete': 'La sesión no reunió todas las rondas válidas necesarias. El valor {best} aparece solo como referencia de los datos disponibles y no representa una recomendación terminada.',
  'calibration.conclusionLowSignal': 'Las puntuaciones quedaron demasiado cerca o demasiado bajas para identificar una región estable. El mejor valor observado fue {best}, con {bestScore}, apenas {gap} punto por encima del segundo.',
  'calibration.scoreGapHint': 'Ventaja de {gap} punto sobre el segundo', 'calibration.playerConsistency': 'Consistencia del jugador', 'calibration.playerConsistencyHint': 'Repetición del rendimiento entre bloques y sensibilidades',
  'calibration.strengthExplanation': 'La fuerza de la recomendación considera separación entre valores, consistencia, concordancia entre bloques y validación. Una recolección excelente aún puede producir una recomendación débil cuando los resultados se contradicen.', 'calibration.testedValuesHint': 'El resaltado marca el mejor resultado observado. Solo valores vecinos pueden formar una zona de ajuste.',
  'calibration.collectionQuality': 'Calidad de la recolección', 'calibration.collectionQualityHint': 'Muestras, estabilidad y rondas completadas', 'calibration.recommendationStrengthHint': 'Claridad con la que los datos sostienen la dirección indicada', 'calibration.completedRoundsHint': 'Rondas aceptadas por el control de calidad',
  'calibration.disclaimerV3': 'Estimación experimental de esta sesión de tracking. El punto destacado fue probado realmente. La zona de ajuste aparece solamente cuando sensibilidades adyacentes produjeron un rendimiento equivalente. FOV, ADS, arma, fatiga y mecánicas del juego pueden cambiar la preferencia. Confirma el valor en el campo de práctica antes de adoptar un cambio permanente.',
  'calibration.reasonValidationSplit': 'La comparación final quedó dividida y no confirmó un único punto.',
  'calibration.conclusionValidationSplit': 'La comparación final quedó dividida entre los dos valores probados. El resultado {validationRecord} no confirmó un punto único. Usa {best} solo como referencia provisional o repite la calibración completa otro día.',
  'calibration.validationStatusConfirmed': 'Confirmada',
  'calibration.validationStatusSplit': 'Comparación dividida',
  'calibration.validationStatusReversed': 'Resultado revertido',
  'calibration.validationStatusUnavailable': 'No realizada',
  'calibration.validationConfirmedCount': '{confirmed} de {total} bloques finales favorecieron {value}.',
  'calibration.validationSplitCount': 'La comparación terminó {confirmed}–{alternative}, con {ties} empate(s). {value} lideró el promedio final por {gap} punto(s).',
  'calibration.validationReversedCount': '{value} ganó {alternative} de {total} trayectorias finales y revirtió el resultado inicial.',
  'calibration.refinementStatus': 'Etapa de refinamiento',
  'calibration.refinementCompleted': 'Refinamiento final completado',
  'calibration.refinementCompletedHint': 'El proceso termina aquí para evitar refinamientos sucesivos y falsa precisión.',
  'calibration.refinementNotNeeded': 'Refinamiento no necesario',
  'calibration.refinementNotNeededHint': 'La evidencia ya sostiene una conclusión práctica o requiere una nueva sesión completa.',
  'calibration.validationColumn': 'Validação',
  'calibration.refineFinal': 'Hacer refinamiento final',
  'calibration.finish': 'Usar este resultado',
  'calibration.validationTieShort': 'empate',
  'calibration.validationSplitTieCount': 'La comparación terminó {confirmed}–{alternative}, con {ties} empate(s). El promedio final quedó dentro del margen técnico de igualdad.',
  'calibration.closeReport': 'Cerrar informe',
  'calibration.roundCountCompact': '{measurements} mediciones · {validation} rondas finales',
  'calibration.horizontalFov': 'FOV horizontal', 'calibration.cmPer360': 'Distancia para 360°', 'calibration.cmPer360Unavailable': 'Perfil físico no disponible',
  'calibration.historyTitle': 'Historial de calibración', 'calibration.historyCount': '{count} sesiones guardadas', 'calibration.historyEmpty': 'Completa una calibración válida para iniciar el historial de este juego.', 'calibration.historyPhysicalAverage': 'Promedio físico de las sesiones: {value} cm/360°. El historial muestra estabilidad, pero no modifica el cálculo de la sesión actual.',
  'converter.cmPer360': 'Distancia para 360°',
  'calibration.vsBaseClear': 'frente a la sensibilidad base', 'calibration.formulaExplanationPhysical': 'La precisión mide el tiempo dentro del objetivo. El control convierte el error medio en puntuación. La suavidad usa una medida robusta de los cambios de velocidad. Las sobrepasadas del objetivo restan puntos.',
  'calibration.setupDescriptionPhysical': 'Elige el juego e indica sensibilidad, DPI y FOV horizontal. La sesión usa hasta {rounds} rondas de {seconds} segundos, incluidas dos comparaciones finales entre los valores más sólidos.',
  'calibration.physicalProfile': 'Perfil físico · {dpi} DPI · FOV horizontal {fov}°', 'calibration.relativeProfileNotice': 'Este juego aún no tiene una escala lineal confirmada en $ENSI. La calibración sigue siendo relativa y no muestra cm/360°.',
  'nav.gamepad': 'Control', 'gamepad.diagnostics': 'Diagnóstico de control', 'gamepad.title': 'Prueba de joystick', 'gamepad.subtitle': 'Lectura en tiempo real de botones, analógicos, gatillos y estabilidad del control.', 'gamepad.waitingTitle': 'Conecta y activa el control', 'gamepad.waitingDescription': 'Pulsa cualquier botón del control para que el navegador detecte el dispositivo.', 'gamepad.connectedControllers': 'Controles conectados', 'gamepad.controller': 'Control', 'gamepad.unknown': 'Control desconocido', 'gamepad.index': 'Índice', 'gamepad.timestamp': 'Timestamp', 'gamepad.status': 'Estado', 'gamepad.connected': 'Conectado', 'gamepad.rumble': 'Probar vibración', 'gamepad.pressed': 'Botones pulsados', 'gamepad.leftStick': 'Analógico izquierdo', 'gamepad.rightStick': 'Analógico derecho', 'gamepad.circularity': 'Error de circularidad', 'gamepad.rawAxes': 'Valores brutos de los ejes', 'gamepad.resetPath': 'Limpiar trayectos',

}

const dictionaries = { pt, en, es }
const localeTags: Record<Locale, string> = { pt: 'pt-BR', en: 'en-US', es: 'es-ES' }

function detectLocale(): Locale {
  const saved = localStorage.getItem('sensi-locale')
  if (saved === 'pt' || saved === 'en' || saved === 'es') return saved
  const languages = navigator.languages?.length ? navigator.languages : [navigator.language]
  for (const language of languages) {
    const code = language.toLowerCase().split('-')[0]
    if (code === 'pt' || code === 'en' || code === 'es') return code
  }
  return 'pt'
}

type I18nValue = {
  locale: Locale
  localeTag: string
  setLocale: (locale: Locale) => void
  t: (key: keyof typeof pt, params?: Params) => string
}

const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(detectLocale)
  useEffect(() => {
    document.documentElement.lang = localeTags[locale]
    document.title = dictionaries[locale]['meta.title']
  }, [locale])
  const value = useMemo<I18nValue>(() => ({
    locale,
    localeTag: localeTags[locale],
    setLocale: (next) => { localStorage.setItem('sensi-locale', next); setLocaleState(next) },
    t: (key, params) => {
      let text = dictionaries[locale][key] ?? pt[key] ?? key
      for (const [name, replacement] of Object.entries(params ?? {})) text = text.replaceAll(`{${name}}`, String(replacement))
      return text
    },
  }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

// The hook shares this module with its provider so consumers import one i18n surface.
// eslint-disable-next-line react-refresh/only-export-components
export function useI18n() {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}
